/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/com/qualcomm/qti/sensor/SensorInterfaceSomeIPStubAdapter.hpp>
#include <v1/com/qualcomm/qti/sensor/SensorInterface.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace com {
namespace qualcomm {
namespace qti {
namespace sensor {

std::shared_ptr<CommonAPI::SomeIP::StubAdapter> createSensorInterfaceSomeIPStubAdapter(
                   const CommonAPI::SomeIP::Address &_address,
                   const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                   const std::shared_ptr<CommonAPI::StubBase> &_stub) {
    return std::make_shared< SensorInterfaceSomeIPStubAdapter<::v1::com::qualcomm::qti::sensor::SensorInterfaceStub>>(_address, _connection, _stub);
}

void initializeSensorInterfaceSomeIPStubAdapter() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:com.qualcomm.qti.sensor.SensorInterface:v1_0:com.qualcomm.qti.sensor.SensorInterface",
         0xee01, 0x1, 1, 0);
    CommonAPI::SomeIP::Factory::get()->registerStubAdapterCreateMethod(
        "com.qualcomm.qti.sensor.SensorInterface:v1_0",
        &createSensorInterfaceSomeIPStubAdapter);
}

INITIALIZER(registerSensorInterfaceSomeIPStubAdapter) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeSensorInterfaceSomeIPStubAdapter);
}

} // namespace sensor
} // namespace qti
} // namespace qualcomm
} // namespace com
} // namespace v1
