/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */

#ifndef V1_COM_QUALCOMM_QTI_SENSOR_SENSOR_INTERFACE_TYPES_SOMEIP_DEPLOYMENT_HPP_
#define V1_COM_QUALCOMM_QTI_SENSOR_SENSOR_INTERFACE_TYPES_SOMEIP_DEPLOYMENT_HPP_


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif
#include <CommonAPI/SomeIP/Deployment.hpp>
#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace com {
namespace qualcomm {
namespace qti {
namespace sensor {
namespace SensorInterfaceTypes_ {

// typecollection-specific deployment types
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> SensorReturnTDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> SensorTypeTDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> SensorStateTDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> SensorServiceStateMaskTDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorReturnTDeployment_t
> SensorResponseTDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::IntegerDeployment<int32_t>,
    CommonAPI::SomeIP::StringDeployment,
    CommonAPI::SomeIP::StringDeployment,
    CommonAPI::SomeIP::IntegerDeployment<int32_t>,
    CommonAPI::SomeIP::IntegerDeployment<int32_t>,
    CommonAPI::EmptyDeployment,
    CommonAPI::SomeIP::IntegerDeployment<int32_t>,
    CommonAPI::SomeIP::IntegerDeployment<int32_t>,
    CommonAPI::SomeIP::ArrayDeployment<
        CommonAPI::EmptyDeployment
    >,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> SensorInfoTDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::ArrayDeployment<
        CommonAPI::SomeIP::StructDeployment<
            CommonAPI::SomeIP::IntegerDeployment<int32_t>,
            CommonAPI::SomeIP::StringDeployment,
            CommonAPI::SomeIP::StringDeployment,
            CommonAPI::SomeIP::IntegerDeployment<int32_t>,
            CommonAPI::SomeIP::IntegerDeployment<int32_t>,
            CommonAPI::EmptyDeployment,
            CommonAPI::SomeIP::IntegerDeployment<int32_t>,
            CommonAPI::SomeIP::IntegerDeployment<int32_t>,
            CommonAPI::SomeIP::ArrayDeployment<
                CommonAPI::EmptyDeployment
            >,
            CommonAPI::EmptyDeployment,
            CommonAPI::EmptyDeployment
        >
    >,
    CommonAPI::SomeIP::IntegerDeployment<int32_t>
> GetSensorListResponseTDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::IntegerDeployment<int32_t>,
    CommonAPI::EmptyDeployment,
    CommonAPI::SomeIP::IntegerDeployment<int32_t>
> SensorConfigRequestTDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::IntegerDeployment<int32_t>,
    ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorStateTDeployment_t
> SensorControlRequestTDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> SensorUncalibratedEventTDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::IntegerDeployment<int32_t>,
    CommonAPI::SomeIP::IntegerDeployment<int32_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint64_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint64_t>,
    CommonAPI::SomeIP::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >
> SensorImuEventTDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> SensorHeadingEventTDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::IntegerDeployment<int32_t>,
    CommonAPI::SomeIP::IntegerDeployment<int32_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint64_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint64_t>,
    CommonAPI::SomeIP::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >
> SensorHeadEventTDeployment_t;


// typecollection-specific deployments
COMMONAPI_EXPORT extern SensorReturnTDeployment_t SensorReturnTDeployment;
COMMONAPI_EXPORT extern SensorTypeTDeployment_t SensorTypeTDeployment;
COMMONAPI_EXPORT extern SensorStateTDeployment_t SensorStateTDeployment;
COMMONAPI_EXPORT extern SensorServiceStateMaskTDeployment_t SensorServiceStateMaskTDeployment;
COMMONAPI_EXPORT extern ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorResponseTDeployment_t SensorResponseTDeployment;
COMMONAPI_EXPORT extern ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorControlRequestTDeployment_t SensorControlRequestTDeployment;

} // namespace SensorInterfaceTypes_
} // namespace sensor
} // namespace qti
} // namespace qualcomm
} // namespace com
} // namespace v1

#endif // V1_COM_QUALCOMM_QTI_SENSOR_SENSOR_INTERFACE_TYPES_SOMEIP_DEPLOYMENT_HPP_
