/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/com/qualcomm/qti/sensor/SensorInterfaceSomeIPProxy.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace com {
namespace qualcomm {
namespace qti {
namespace sensor {

std::shared_ptr<CommonAPI::SomeIP::Proxy> createSensorInterfaceSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection) {
    return std::make_shared< SensorInterfaceSomeIPProxy>(_address, _connection);
}

void initializeSensorInterfaceSomeIPProxy() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:com.qualcomm.qti.sensor.SensorInterface:v1_0:com.qualcomm.qti.sensor.SensorInterface",
        0xee01, 0x1, 1, 0);
    CommonAPI::SomeIP::Factory::get()->registerProxyCreateMethod(
        "com.qualcomm.qti.sensor.SensorInterface:v1_0",
        &createSensorInterfaceSomeIPProxy);
}

INITIALIZER(registerSensorInterfaceSomeIPProxy) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeSensorInterfaceSomeIPProxy);
}

SensorInterfaceSomeIPProxy::SensorInterfaceSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection)
        : CommonAPI::SomeIP::Proxy(_address, _connection),
          sensorCapabilities_(*this, 0x80e8, CommonAPI::SomeIP::event_id_t(0x80e9), CommonAPI::SomeIP::event_type_e::ET_EVENT , CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, std::make_tuple(&::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorServiceStateMaskTDeployment)),
          sensorConfigUpdate_(*this, 0x80e8, CommonAPI::SomeIP::event_id_t(0x80ea), CommonAPI::SomeIP::event_type_e::ET_EVENT , CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr), static_cast< CommonAPI::EmptyDeployment* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr))),
          sensorImuDataRead_(*this, 0x80e8, CommonAPI::SomeIP::event_id_t(0x80eb), CommonAPI::SomeIP::event_type_e::ET_EVENT , CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, std::make_tuple(static_cast< CommonAPI::SomeIP::ArrayDeployment< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorImuEventTDeployment_t >* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr))),
          sensorHeadingDataRead_(*this, 0x80e8, CommonAPI::SomeIP::event_id_t(0x80ec), CommonAPI::SomeIP::event_type_e::ET_EVENT , CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, std::make_tuple(static_cast< CommonAPI::SomeIP::ArrayDeployment< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorHeadEventTDeployment_t >* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr)))
{
}

SensorInterfaceSomeIPProxy::~SensorInterfaceSomeIPProxy() {
    completed_.set_value();
}


SensorInterfaceSomeIPProxy::SensorCapabilitiesEvent& SensorInterfaceSomeIPProxy::getSensorCapabilitiesEvent() {
    return sensorCapabilities_;
}
SensorInterfaceSomeIPProxy::SensorConfigUpdateEvent& SensorInterfaceSomeIPProxy::getSensorConfigUpdateEvent() {
    return sensorConfigUpdate_;
}
SensorInterfaceSomeIPProxy::SensorImuDataReadEvent& SensorInterfaceSomeIPProxy::getSensorImuDataReadEvent() {
    return sensorImuDataRead_;
}
SensorInterfaceSomeIPProxy::SensorHeadingDataReadEvent& SensorInterfaceSomeIPProxy::getSensorHeadingDataReadEvent() {
    return sensorHeadingDataRead_;
}

void SensorInterfaceSomeIPProxy::RegisterSensorClientReq(CommonAPI::CallStatus &_internalCallStatus, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT &_SensorResponse, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorReturnTDeployment_t> deploy_SensorResponse(&::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorReturnTDeployment);
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT,
                ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorReturnTDeployment_t
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x7d01),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        _internalCallStatus,
        deploy_SensorResponse);
    _SensorResponse = deploy_SensorResponse.getValue();
}

std::future<CommonAPI::CallStatus> SensorInterfaceSomeIPProxy::RegisterSensorClientReqAsync(RegisterSensorClientReqAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorReturnTDeployment_t> deploy_SensorResponse(&::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorReturnTDeployment);
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT,
                ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorReturnTDeployment_t
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x7d01),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorReturnTDeployment_t > _SensorResponse) {
            if (_callback)
                _callback(_internalCallStatus, _SensorResponse.getValue());
        },
        std::make_tuple(deploy_SensorResponse));
}

void SensorInterfaceSomeIPProxy::DeRegisterSensorClientReq(CommonAPI::CallStatus &_internalCallStatus, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT &_SensorResponse, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorReturnTDeployment_t> deploy_SensorResponse(&::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorReturnTDeployment);
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT,
                ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorReturnTDeployment_t
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x7d02),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        _internalCallStatus,
        deploy_SensorResponse);
    _SensorResponse = deploy_SensorResponse.getValue();
}

std::future<CommonAPI::CallStatus> SensorInterfaceSomeIPProxy::DeRegisterSensorClientReqAsync(DeRegisterSensorClientReqAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorReturnTDeployment_t> deploy_SensorResponse(&::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorReturnTDeployment);
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT,
                ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorReturnTDeployment_t
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x7d02),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorReturnTDeployment_t > _SensorResponse) {
            if (_callback)
                _callback(_internalCallStatus, _SensorResponse.getValue());
        },
        std::make_tuple(deploy_SensorResponse));
}

void SensorInterfaceSomeIPProxy::GetSensorListReq(CommonAPI::CallStatus &_internalCallStatus, std::vector< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorInfoT > &_SensorList, int32_t &_count, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< std::vector< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorInfoT >, CommonAPI::SomeIP::ArrayDeployment< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorInfoTDeployment_t >> deploy_SensorList(static_cast< CommonAPI::SomeIP::ArrayDeployment< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorInfoTDeployment_t >* >(nullptr));
    CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t>> deploy_count(static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::vector< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorInfoT >,
                CommonAPI::SomeIP::ArrayDeployment< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorInfoTDeployment_t >
            >,
            CommonAPI::Deployable<
                int32_t,
                CommonAPI::SomeIP::IntegerDeployment<int32_t>
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x7d03),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        _internalCallStatus,
        deploy_SensorList, deploy_count);
    _SensorList = deploy_SensorList.getValue();
    _count = deploy_count.getValue();
}

std::future<CommonAPI::CallStatus> SensorInterfaceSomeIPProxy::GetSensorListReqAsync(GetSensorListReqAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< std::vector< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorInfoT >, CommonAPI::SomeIP::ArrayDeployment< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorInfoTDeployment_t >> deploy_SensorList(static_cast< CommonAPI::SomeIP::ArrayDeployment< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorInfoTDeployment_t >* >(nullptr));
    CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t>> deploy_count(static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::vector< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorInfoT >,
                CommonAPI::SomeIP::ArrayDeployment< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorInfoTDeployment_t >
            >,
            CommonAPI::Deployable<
                int32_t,
                CommonAPI::SomeIP::IntegerDeployment<int32_t>
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x7d03),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< std::vector< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorInfoT >, CommonAPI::SomeIP::ArrayDeployment< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorInfoTDeployment_t > > _SensorList, CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t> > _count) {
            if (_callback)
                _callback(_internalCallStatus, _SensorList.getValue(), _count.getValue());
        },
        std::make_tuple(deploy_SensorList, deploy_count));
}

void SensorInterfaceSomeIPProxy::SensorConfigReq(int32_t _sensorId, float _samplingRate, int32_t _batchCount, CommonAPI::CallStatus &_internalCallStatus, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT &_SensorResponse, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t>> deploy_sensorId(_sensorId, static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr));
    CommonAPI::Deployable< float, CommonAPI::EmptyDeployment> deploy_samplingRate(_samplingRate, static_cast< CommonAPI::EmptyDeployment* >(nullptr));
    CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t>> deploy_batchCount(_batchCount, static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr));
    CommonAPI::Deployable< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorReturnTDeployment_t> deploy_SensorResponse(&::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorReturnTDeployment);
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                int32_t,
                CommonAPI::SomeIP::IntegerDeployment<int32_t>
            >,
            CommonAPI::Deployable<
                float,
                CommonAPI::EmptyDeployment
            >,
            CommonAPI::Deployable<
                int32_t,
                CommonAPI::SomeIP::IntegerDeployment<int32_t>
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT,
                ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorReturnTDeployment_t
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x7d04),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_sensorId, deploy_samplingRate, deploy_batchCount,
        _internalCallStatus,
        deploy_SensorResponse);
    _SensorResponse = deploy_SensorResponse.getValue();
}

std::future<CommonAPI::CallStatus> SensorInterfaceSomeIPProxy::SensorConfigReqAsync(const int32_t &_sensorId, const float &_samplingRate, const int32_t &_batchCount, SensorConfigReqAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t>> deploy_sensorId(_sensorId, static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr));
    CommonAPI::Deployable< float, CommonAPI::EmptyDeployment> deploy_samplingRate(_samplingRate, static_cast< CommonAPI::EmptyDeployment* >(nullptr));
    CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t>> deploy_batchCount(_batchCount, static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr));
    CommonAPI::Deployable< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorReturnTDeployment_t> deploy_SensorResponse(&::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorReturnTDeployment);
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                int32_t,
                CommonAPI::SomeIP::IntegerDeployment<int32_t>
            >,
            CommonAPI::Deployable<
                float,
                CommonAPI::EmptyDeployment
            >,
            CommonAPI::Deployable<
                int32_t,
                CommonAPI::SomeIP::IntegerDeployment<int32_t>
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT,
                ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorReturnTDeployment_t
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x7d04),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_sensorId, deploy_samplingRate, deploy_batchCount,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorReturnTDeployment_t > _SensorResponse) {
            if (_callback)
                _callback(_internalCallStatus, _SensorResponse.getValue());
        },
        std::make_tuple(deploy_SensorResponse));
}

void SensorInterfaceSomeIPProxy::SensorControlReq(int32_t _sensorId, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorStateT _sensorState, CommonAPI::CallStatus &_internalCallStatus, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT &_SensorResponse, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t>> deploy_sensorId(_sensorId, static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr));
    CommonAPI::Deployable< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorStateT, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorStateTDeployment_t> deploy_sensorState(_sensorState, &::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorStateTDeployment);
    CommonAPI::Deployable< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorReturnTDeployment_t> deploy_SensorResponse(&::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorReturnTDeployment);
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                int32_t,
                CommonAPI::SomeIP::IntegerDeployment<int32_t>
            >,
            CommonAPI::Deployable<
                ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorStateT,
                ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorStateTDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT,
                ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorReturnTDeployment_t
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x7d05),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_sensorId, deploy_sensorState,
        _internalCallStatus,
        deploy_SensorResponse);
    _SensorResponse = deploy_SensorResponse.getValue();
}

std::future<CommonAPI::CallStatus> SensorInterfaceSomeIPProxy::SensorControlReqAsync(const int32_t &_sensorId, const ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorStateT &_sensorState, SensorControlReqAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t>> deploy_sensorId(_sensorId, static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr));
    CommonAPI::Deployable< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorStateT, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorStateTDeployment_t> deploy_sensorState(_sensorState, &::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorStateTDeployment);
    CommonAPI::Deployable< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorReturnTDeployment_t> deploy_SensorResponse(&::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorReturnTDeployment);
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                int32_t,
                CommonAPI::SomeIP::IntegerDeployment<int32_t>
            >,
            CommonAPI::Deployable<
                ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorStateT,
                ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorStateTDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT,
                ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorReturnTDeployment_t
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x7d05),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_sensorId, deploy_sensorState,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorReturnTDeployment_t > _SensorResponse) {
            if (_callback)
                _callback(_internalCallStatus, _SensorResponse.getValue());
        },
        std::make_tuple(deploy_SensorResponse));
}

void SensorInterfaceSomeIPProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
    ownVersionMajor = 1;
    ownVersionMinor = 0;
}

std::future<void> SensorInterfaceSomeIPProxy::getCompletionFuture() {
    return completed_.get_future();
}

} // namespace sensor
} // namespace qti
} // namespace qualcomm
} // namespace com
} // namespace v1
