/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_COM_QUALCOMM_QTI_SENSOR_SENSOR_INTERFACE_HPP_
#define V0_COM_QUALCOMM_QTI_SENSOR_SENSOR_INTERFACE_HPP_




#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <CommonAPI/Types.hpp>
#include <CommonAPI/Variant.hpp>
#include <cstdint>
#include <memory>
#include <string>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace com {
namespace qualcomm {
namespace qti {
namespace sensor {

class SensorInterface {
public:
    virtual ~SensorInterface() { }

    static inline const char* getInterface();
    static inline CommonAPI::Version getInterfaceVersion();
    
    struct Sensortype : CommonAPI::Enumeration< uint32_t> {
        enum Literal : uint32_t {
            SENSOR_TYPE_ACCELEROMETER = 1,
            SENSOR_TYPE_GYROSCOPE = 4,
            SENSOR_TYPE_GYROSCOPE_UNCALIBRATED = 16,
            SENSOR_TYPE_ACCELEROMETER_UNCALIBRATED = 35,
            SENSOR_TYPE_HEADING = 5
        };
    
        Sensortype()
            : CommonAPI::Enumeration< uint32_t>(static_cast< uint32_t>(Literal::SENSOR_TYPE_ACCELEROMETER)) {}
        Sensortype(Literal _literal)
            : CommonAPI::Enumeration< uint32_t>(static_cast< uint32_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< uint32_t>(Literal::SENSOR_TYPE_ACCELEROMETER):
                case static_cast< uint32_t>(Literal::SENSOR_TYPE_GYROSCOPE):
                case static_cast< uint32_t>(Literal::SENSOR_TYPE_GYROSCOPE_UNCALIBRATED):
                case static_cast< uint32_t>(Literal::SENSOR_TYPE_ACCELEROMETER_UNCALIBRATED):
                case static_cast< uint32_t>(Literal::SENSOR_TYPE_HEADING):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const Sensortype &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const Sensortype &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const Sensortype &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const Sensortype &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const Sensortype &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const Sensortype &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< uint32_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< uint32_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< uint32_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< uint32_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< uint32_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< uint32_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< uint32_t>(Literal::SENSOR_TYPE_ACCELEROMETER): return "SENSOR_TYPE_ACCELEROMETER";
            case static_cast< uint32_t>(Literal::SENSOR_TYPE_GYROSCOPE): return "SENSOR_TYPE_GYROSCOPE";
            case static_cast< uint32_t>(Literal::SENSOR_TYPE_GYROSCOPE_UNCALIBRATED): return "SENSOR_TYPE_GYROSCOPE_UNCALIBRATED";
            case static_cast< uint32_t>(Literal::SENSOR_TYPE_ACCELEROMETER_UNCALIBRATED): return "SENSOR_TYPE_ACCELEROMETER_UNCALIBRATED";
            case static_cast< uint32_t>(Literal::SENSOR_TYPE_HEADING): return "SENSOR_TYPE_HEADING";
            default: return "UNDEFINED";
            }
        }
    };
    
    struct SensorResponse : CommonAPI::Enumeration< int32_t> {
        enum Literal : int32_t {
            SENSOR_RESPONSE_SUCCESS = 0,
            SENSOR_ERROR_CLIENT_REGISTER_FAILED = -1,
            SENSOR_ERROR_INVALID_CLIENT = -2,
            SENSOR_ERROR_INVALID_INPUT_PARAMETER = -3,
            SENSOR_ERROR_CONTROL_FAILED = -4,
            SENSOR_ERROR_CONFIG_FAILED = -5,
            SENSOR_ERROR_NO_SENSORS_FOUND = -6,
            SENSOR_ERROR_TRACKING_FAILED = -7,
            SENSOR_ERROR_UNKNOWN = -8
        };
    
        SensorResponse()
            : CommonAPI::Enumeration< int32_t>(static_cast< int32_t>(Literal::SENSOR_RESPONSE_SUCCESS)) {}
        SensorResponse(Literal _literal)
            : CommonAPI::Enumeration< int32_t>(static_cast< int32_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< int32_t>(Literal::SENSOR_RESPONSE_SUCCESS):
                case static_cast< int32_t>(Literal::SENSOR_ERROR_CLIENT_REGISTER_FAILED):
                case static_cast< int32_t>(Literal::SENSOR_ERROR_INVALID_CLIENT):
                case static_cast< int32_t>(Literal::SENSOR_ERROR_INVALID_INPUT_PARAMETER):
                case static_cast< int32_t>(Literal::SENSOR_ERROR_CONTROL_FAILED):
                case static_cast< int32_t>(Literal::SENSOR_ERROR_CONFIG_FAILED):
                case static_cast< int32_t>(Literal::SENSOR_ERROR_NO_SENSORS_FOUND):
                case static_cast< int32_t>(Literal::SENSOR_ERROR_TRACKING_FAILED):
                case static_cast< int32_t>(Literal::SENSOR_ERROR_UNKNOWN):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const SensorResponse &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const SensorResponse &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const SensorResponse &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const SensorResponse &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const SensorResponse &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const SensorResponse &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< int32_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< int32_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< int32_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< int32_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< int32_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< int32_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< int32_t>(Literal::SENSOR_RESPONSE_SUCCESS): return "SENSOR_RESPONSE_SUCCESS";
            case static_cast< int32_t>(Literal::SENSOR_ERROR_CLIENT_REGISTER_FAILED): return "SENSOR_ERROR_CLIENT_REGISTER_FAILED";
            case static_cast< int32_t>(Literal::SENSOR_ERROR_INVALID_CLIENT): return "SENSOR_ERROR_INVALID_CLIENT";
            case static_cast< int32_t>(Literal::SENSOR_ERROR_INVALID_INPUT_PARAMETER): return "SENSOR_ERROR_INVALID_INPUT_PARAMETER";
            case static_cast< int32_t>(Literal::SENSOR_ERROR_CONTROL_FAILED): return "SENSOR_ERROR_CONTROL_FAILED";
            case static_cast< int32_t>(Literal::SENSOR_ERROR_CONFIG_FAILED): return "SENSOR_ERROR_CONFIG_FAILED";
            case static_cast< int32_t>(Literal::SENSOR_ERROR_NO_SENSORS_FOUND): return "SENSOR_ERROR_NO_SENSORS_FOUND";
            case static_cast< int32_t>(Literal::SENSOR_ERROR_TRACKING_FAILED): return "SENSOR_ERROR_TRACKING_FAILED";
            case static_cast< int32_t>(Literal::SENSOR_ERROR_UNKNOWN): return "SENSOR_ERROR_UNKNOWN";
            default: return "UNDEFINED";
            }
        }
    };
    
    struct SensorState : CommonAPI::Enumeration< uint32_t> {
        enum Literal : uint32_t {
            SENSOR_DISABLE = 0,
            SENSOR_ENABLE = 1
        };
    
        SensorState()
            : CommonAPI::Enumeration< uint32_t>(static_cast< uint32_t>(Literal::SENSOR_DISABLE)) {}
        SensorState(Literal _literal)
            : CommonAPI::Enumeration< uint32_t>(static_cast< uint32_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< uint32_t>(Literal::SENSOR_DISABLE):
                case static_cast< uint32_t>(Literal::SENSOR_ENABLE):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const SensorState &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const SensorState &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const SensorState &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const SensorState &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const SensorState &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const SensorState &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< uint32_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< uint32_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< uint32_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< uint32_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< uint32_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< uint32_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< uint32_t>(Literal::SENSOR_DISABLE): return "SENSOR_DISABLE";
            case static_cast< uint32_t>(Literal::SENSOR_ENABLE): return "SENSOR_ENABLE";
            default: return "UNDEFINED";
            }
        }
    };
    
    struct SensorCapabilitiesMask : CommonAPI::Enumeration< uint32_t> {
        enum Literal : uint32_t {
            SHD_READY = 1
        };
    
        SensorCapabilitiesMask()
            : CommonAPI::Enumeration< uint32_t>(static_cast< uint32_t>(Literal::SHD_READY)) {}
        SensorCapabilitiesMask(Literal _literal)
            : CommonAPI::Enumeration< uint32_t>(static_cast< uint32_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< uint32_t>(Literal::SHD_READY):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const SensorCapabilitiesMask &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const SensorCapabilitiesMask &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const SensorCapabilitiesMask &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const SensorCapabilitiesMask &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const SensorCapabilitiesMask &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const SensorCapabilitiesMask &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< uint32_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< uint32_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< uint32_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< uint32_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< uint32_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< uint32_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< uint32_t>(Literal::SHD_READY): return "SHD_READY";
            default: return "UNDEFINED";
            }
        }
    };
    struct SensorList : CommonAPI::Struct< int32_t, std::string, std::string, int32_t, int32_t, float, int32_t, int32_t, std::vector< float >, int32_t, float, float> {
    
        SensorList()
        {
            std::get< 0>(values_) = 0;
            std::get< 1>(values_) = "";
            std::get< 2>(values_) = "";
            std::get< 3>(values_) = 0;
            std::get< 4>(values_) = 0;
            std::get< 5>(values_) = 0.0f;
            std::get< 6>(values_) = 0;
            std::get< 7>(values_) = 0;
            std::get< 8>(values_) = std::vector< float >();
            std::get< 9>(values_) = 0;
            std::get< 10>(values_) = 0.0f;
            std::get< 11>(values_) = 0.0f;
        }
        SensorList(const int32_t &_sensorVersion, const std::string &_name, const std::string &_vendor, const int32_t &_sensorId, const int32_t &_type, const float &_maxSamplingRate, const int32_t &_minBatchCount, const int32_t &_maxBatchCount, const std::vector< float > &_odr, const int32_t &_range, const float &_resolution, const float &_maxRange)
        {
            std::get< 0>(values_) = _sensorVersion;
            std::get< 1>(values_) = _name;
            std::get< 2>(values_) = _vendor;
            std::get< 3>(values_) = _sensorId;
            std::get< 4>(values_) = _type;
            std::get< 5>(values_) = _maxSamplingRate;
            std::get< 6>(values_) = _minBatchCount;
            std::get< 7>(values_) = _maxBatchCount;
            std::get< 8>(values_) = _odr;
            std::get< 9>(values_) = _range;
            std::get< 10>(values_) = _resolution;
            std::get< 11>(values_) = _maxRange;
        }
        inline const int32_t &getSensorVersion() const { return std::get< 0>(values_); }
        inline void setSensorVersion(const int32_t &_value) { std::get< 0>(values_) = _value; }
        inline const std::string &getName() const { return std::get< 1>(values_); }
        inline void setName(const std::string &_value) { std::get< 1>(values_) = _value; }
        inline const std::string &getVendor() const { return std::get< 2>(values_); }
        inline void setVendor(const std::string &_value) { std::get< 2>(values_) = _value; }
        inline const int32_t &getSensorId() const { return std::get< 3>(values_); }
        inline void setSensorId(const int32_t &_value) { std::get< 3>(values_) = _value; }
        inline const int32_t &getType() const { return std::get< 4>(values_); }
        inline void setType(const int32_t &_value) { std::get< 4>(values_) = _value; }
        inline const float &getMaxSamplingRate() const { return std::get< 5>(values_); }
        inline void setMaxSamplingRate(const float &_value) { std::get< 5>(values_) = _value; }
        inline const int32_t &getMinBatchCount() const { return std::get< 6>(values_); }
        inline void setMinBatchCount(const int32_t &_value) { std::get< 6>(values_) = _value; }
        inline const int32_t &getMaxBatchCount() const { return std::get< 7>(values_); }
        inline void setMaxBatchCount(const int32_t &_value) { std::get< 7>(values_) = _value; }
        inline const std::vector< float > &getOdr() const { return std::get< 8>(values_); }
        inline void setOdr(const std::vector< float > &_value) { std::get< 8>(values_) = _value; }
        inline const int32_t &getRange() const { return std::get< 9>(values_); }
        inline void setRange(const int32_t &_value) { std::get< 9>(values_) = _value; }
        inline const float &getResolution() const { return std::get< 10>(values_); }
        inline void setResolution(const float &_value) { std::get< 10>(values_) = _value; }
        inline const float &getMaxRange() const { return std::get< 11>(values_); }
        inline void setMaxRange(const float &_value) { std::get< 11>(values_) = _value; }
        inline bool operator==(const SensorList& _other) const {
        return (getSensorVersion() == _other.getSensorVersion() && getName() == _other.getName() && getVendor() == _other.getVendor() && getSensorId() == _other.getSensorId() && getType() == _other.getType() && getMaxSamplingRate() == _other.getMaxSamplingRate() && getMinBatchCount() == _other.getMinBatchCount() && getMaxBatchCount() == _other.getMaxBatchCount() && getOdr() == _other.getOdr() && getRange() == _other.getRange() && getResolution() == _other.getResolution() && getMaxRange() == _other.getMaxRange());
        }
        inline bool operator!=(const SensorList &_other) const {
            return !((*this) == _other);
        }
    
    };
    struct SensorHeadingEvent : CommonAPI::Struct< float, float> {
    
        SensorHeadingEvent()
        {
            std::get< 0>(values_) = 0.0f;
            std::get< 1>(values_) = 0.0f;
        }
        SensorHeadingEvent(const float &_heading, const float &_accuracy)
        {
            std::get< 0>(values_) = _heading;
            std::get< 1>(values_) = _accuracy;
        }
        inline const float &getHeading() const { return std::get< 0>(values_); }
        inline void setHeading(const float &_value) { std::get< 0>(values_) = _value; }
        inline const float &getAccuracy() const { return std::get< 1>(values_); }
        inline void setAccuracy(const float &_value) { std::get< 1>(values_) = _value; }
        inline bool operator==(const SensorHeadingEvent& _other) const {
        return (getHeading() == _other.getHeading() && getAccuracy() == _other.getAccuracy());
        }
        inline bool operator!=(const SensorHeadingEvent &_other) const {
            return !((*this) == _other);
        }
    
    };
    struct SensorUncalibratedEvent : CommonAPI::Struct< float, float, float, float, float, float> {
    
        SensorUncalibratedEvent()
        {
            std::get< 0>(values_) = 0.0f;
            std::get< 1>(values_) = 0.0f;
            std::get< 2>(values_) = 0.0f;
            std::get< 3>(values_) = 0.0f;
            std::get< 4>(values_) = 0.0f;
            std::get< 5>(values_) = 0.0f;
        }
        SensorUncalibratedEvent(const float &_x_uncalib, const float &_y_uncalib, const float &_z_uncalib, const float &_x_bias, const float &_y_bias, const float &_z_bias)
        {
            std::get< 0>(values_) = _x_uncalib;
            std::get< 1>(values_) = _y_uncalib;
            std::get< 2>(values_) = _z_uncalib;
            std::get< 3>(values_) = _x_bias;
            std::get< 4>(values_) = _y_bias;
            std::get< 5>(values_) = _z_bias;
        }
        inline const float &getX_uncalib() const { return std::get< 0>(values_); }
        inline void setX_uncalib(const float &_value) { std::get< 0>(values_) = _value; }
        inline const float &getY_uncalib() const { return std::get< 1>(values_); }
        inline void setY_uncalib(const float &_value) { std::get< 1>(values_) = _value; }
        inline const float &getZ_uncalib() const { return std::get< 2>(values_); }
        inline void setZ_uncalib(const float &_value) { std::get< 2>(values_) = _value; }
        inline const float &getX_bias() const { return std::get< 3>(values_); }
        inline void setX_bias(const float &_value) { std::get< 3>(values_) = _value; }
        inline const float &getY_bias() const { return std::get< 4>(values_); }
        inline void setY_bias(const float &_value) { std::get< 4>(values_) = _value; }
        inline const float &getZ_bias() const { return std::get< 5>(values_); }
        inline void setZ_bias(const float &_value) { std::get< 5>(values_) = _value; }
        inline bool operator==(const SensorUncalibratedEvent& _other) const {
        return (getX_uncalib() == _other.getX_uncalib() && getY_uncalib() == _other.getY_uncalib() && getZ_uncalib() == _other.getZ_uncalib() && getX_bias() == _other.getX_bias() && getY_bias() == _other.getY_bias() && getZ_bias() == _other.getZ_bias());
        }
        inline bool operator!=(const SensorUncalibratedEvent &_other) const {
            return !((*this) == _other);
        }
    
    };
    typedef CommonAPI::Variant< SensorUncalibratedEvent, SensorHeadingEvent>  SensorData;
    struct SensorEvent : CommonAPI::Struct< int32_t, int32_t, int64_t, int64_t, SensorData> {
    
        SensorEvent()
        {
            std::get< 0>(values_) = 0;
            std::get< 1>(values_) = 0;
            std::get< 2>(values_) = 0;
            std::get< 3>(values_) = 0;
            std::get< 4>(values_) = SensorData();
        }
        SensorEvent(const int32_t &_sensorId, const int32_t &_type, const int64_t &_timestamp, const int64_t &_gptptimestamp, const SensorData &_data)
        {
            std::get< 0>(values_) = _sensorId;
            std::get< 1>(values_) = _type;
            std::get< 2>(values_) = _timestamp;
            std::get< 3>(values_) = _gptptimestamp;
            std::get< 4>(values_) = _data;
        }
        inline const int32_t &getSensorId() const { return std::get< 0>(values_); }
        inline void setSensorId(const int32_t &_value) { std::get< 0>(values_) = _value; }
        inline const int32_t &getType() const { return std::get< 1>(values_); }
        inline void setType(const int32_t &_value) { std::get< 1>(values_) = _value; }
        inline const int64_t &getTimestamp() const { return std::get< 2>(values_); }
        inline void setTimestamp(const int64_t &_value) { std::get< 2>(values_) = _value; }
        inline const int64_t &getGptptimestamp() const { return std::get< 3>(values_); }
        inline void setGptptimestamp(const int64_t &_value) { std::get< 3>(values_) = _value; }
        inline const SensorData &getData() const { return std::get< 4>(values_); }
        inline void setData(const SensorData &_value) { std::get< 4>(values_) = _value; }
        inline bool operator==(const SensorEvent& _other) const {
        return (getSensorId() == _other.getSensorId() && getType() == _other.getType() && getTimestamp() == _other.getTimestamp() && getGptptimestamp() == _other.getGptptimestamp() && getData() == _other.getData());
        }
        inline bool operator!=(const SensorEvent &_other) const {
            return !((*this) == _other);
        }
    
    };
};

const char* SensorInterface::getInterface() {
    return ("com.qualcomm.qti.sensor.SensorInterface:v0_1");
}

CommonAPI::Version SensorInterface::getInterfaceVersion() {
    return CommonAPI::Version(0, 1);
}


} // namespace sensor
} // namespace qti
} // namespace qualcomm
} // namespace com
} // namespace v0

namespace CommonAPI {
}


// Compatibility
namespace v0_1 = v0;

#endif // V0_COM_QUALCOMM_QTI_SENSOR_SENSOR_INTERFACE_HPP_
