# Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
#    SPDX-License-Identifier: BSD-3-Clause-Clear */

syntax = "proto3";

package sdv.connectivity.sensor;

import "syntax/vsidl.proto";
import "syntax/sdvsidl.proto";
import "google/protobuf/empty.proto";
import "catalog/sdv/connectivity/sensor/common/sensor_types.proto";

message SensorConfigRequestT {
  /** Sensor identifier **/
  int32 sensor_id = 1;
  /** Sensor sampling rate request **/
  float sampling_rate = 2;
  /** Sensor batch count request **/
  int32 batch_count = 3;
}

message SensorControlRequestT {
  /** Sensor identifier **/
  int32 sensor_id = 1;
  /** Sensor enable and disable request **/
  SensorStateT sensor_state = 2;
}

message SensorResponseT {
  SensorReturnT return = 1;
}

message GetSensorListResponseT {
  repeated SensorInfoT sensors = 1
  [(sdv.vsidl.repeated_field_max_count) = 10];
  int32 count = 2;
}

// It's RPC interface definition for Sensor Interface APIs
service SensorInterface {
  option(sdv.sdvsidl.service_description) = "Sensor RPC interface definition"
    "for Sensor Client APIs";
  option (sdv.sdvsidl.service_system_owner) = S21_MULTIMEDIA;

  rpc RegisterSensorClientReq (google.protobuf.Empty)
    returns (SensorResponseT) {
    option(sdv.sdvsidl.method_description) = "Register new sensor client \n"
      "Creates an instance of new SensorClient \n"
      "on Success of new client creation SensorServiceStateT will be called \n"
      "to notify the status of sensor service through \n"
      "SensorServiceStateMaskT \n"
      "@returns: SensorResponseT";
  }

  rpc DeRegisterSensorClientReq (google.protobuf.Empty)
    returns (SensorResponseT) {
    option(sdv.sdvsidl.method_description) = "DeRegister sensor client \n"
      "Delete instance of SensorClient \n"
      "@returns: SensorResponseT";
  }

  rpc GetSensorListReq (google.protobuf.Empty)
    returns (GetSensorListResponseT) {
    option(sdv.sdvsidl.method_description) = "get the sensor list \n"
      "It will returns the list of sensors supported by hardware, \n"
      "see “SensorInfoT” for details on how the sensors are defined. \n"
      "The “count” represesnt number of sensors in the list, \n"
      "basically it represensts array size of pointer to SensorInfoT, \n"
      "to access each sensor \n" 
      "need to loop the SensorInfoT from 0 to count ex: if count is 2 then \n"
      "for(int i=0; i< count; i++) \n"
      "where “SensorInfoT[i]” represent each sensor \n"
      "@param[out] SensorInfoT: contains sensor information of sensor \n"
      "@param[out] count: total number of sensor supported \n"
      "@returns: SensorResponseT";
  }

  rpc SensorConfigReq (SensorConfigRequestT)
    returns (SensorResponseT) {
    option(sdv.sdvsidl.method_description) = "Configure sensor \n"
      "for interested sampling rate and batch count \n"
      "Configure the sensor identified by sensor_id with given parameters \n"
      "The sampling rate should be sampling rate supported by SensorInfoT \n"
      "and should be less than or equal to maxSampling rate reported by \n"
      "sensor list, its in HZ. The batching count should not exceed \n"
      "maxBatchCount provided by SensorInfoT. \n"
      "The SensorConfigUpdateT will be invoked to notify client about \n"
      "sensor configured sampling rate and batch count \n"
      "@param[in]  sensor_id: sensor identifier. \n"
      "@param[in]  sampling_rate: sampling rate of sensors in HZ. \n"
      "@param[in]  batch_count: batch count of sensor events \n"
      "@returns:   SensorResponseT";
  }

  rpc SensorControlReq (SensorControlRequestT)
    returns (SensorResponseT) {
    option(sdv.sdvsidl.method_description) = "Activates/deactivates a sensor \n"
      "Activates or deactivates the sensor, sensor’s sensor_id is defined by \n"
      "the sensor_id field of SensorInfoT structure used to activate and \n"
      "deactivate the respective sensor. \n"
      "sensorState is set to SENSOR_STATE_ENABLE to activate the sensor or \n"
      "set to SENSOR_STATE_DISABLE to deactivate the sensor. \n"
      "Activate/Deactivate the sensor identified by sensor_id, \n"
      "in order to get the sensor data, \n"
      "enabling the sensor is not enough, the client must configure sensor \n"
      "by calling SensorConfigReq API \n"
      "@param[in] sensor_id: sensor identifier \n"
      "@param[in] sensorState: SENSOR_STATE_ENABLE to activate and \n"
      "SENSOR_STATE_DISABLE to deactivate the sensor. \n"
      "@returns:  SensorResponseT";
  }
}
