/** Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
    SPDX-License-Identifier: BSD-3-Clause-Clear **/

syntax = "proto3";

package sdv.connectivity.sensor;

import "syntax/sdvsidl.proto";
import "syntax/vsidl.proto";

enum SensorReturnT {
  SENSOR_RETURN_UNKNOWN = 0
  [(sdv.sdvsidl.litteral_description) = "Unknown"];
  SENSOR_RETURN_SUCCESS = 1
  [(sdv.sdvsidl.litteral_description) = "On Success"];
  SENSOR_RETURN_ERROR_CLIENT_REGISTER_FAILED = 2
  [(sdv.sdvsidl.litteral_description) =
  "On Client is not registered to Sensor HAL Daemon"];
  SENSOR_RETURN_ERROR_INVALID_CLIENT = 3
  [(sdv.sdvsidl.litteral_description) =
  "On Client is not generated while registering the client"];
  SENSOR_RETURN_ERROR_INVALID_INPUT_PARAMETER = 4
  [(sdv.sdvsidl.litteral_description) =
  "On Invalid input parameteres from respective API"];
  SENSOR_RETURN_ERROR_CONTROL_FAILED = 5
  [(sdv.sdvsidl.litteral_description) =
  "On Physical Sensor Enable/Disable failed"];
  SENSOR_RETURN_ERROR_CONFIG_FAILED = 6
  [(sdv.sdvsidl.litteral_description) =
  "On Physical Sensor Config failed"];
  SENSOR_RETURN_ERROR_NO_SENSORS_FOUND = 7
  [(sdv.sdvsidl.litteral_description) =
  "On No sensors supported in h/w"];
  SENSOR_RETURN_ERROR_TRACKING_FAILED = 8
  [(sdv.sdvsidl.litteral_description) =
  "On sensor is activated and configured"];
  SENSOR_RETURN_ERROR_UNKNOWN = 9
  [(sdv.sdvsidl.litteral_description) =
  "On Unknown error"];
}

enum SensorStateT {
  SENSOR_STATE_UNKNOWN = 0;
  /**Disable the sensor**/
  SENSOR_STATE_DISABLE = 1;
  /**Enable the sensor**/
  SENSOR_STATE_ENABLE = 2;
}

/** @brief SENSOR_TYPES <br/>
    sensor Types: Possible Sensor Types represented “SensorInfoT->type”
**/
enum SensorTypeT {
  SENSOR_TYPE_META_UNKNOWN = 0;
  /** SENSOR_TYPE_META_DATA is a special token used to populate the
      sensors_meta_data_event structure. It doesn't correspond to a physical
      sensor. sensors_meta_data_event are special, they exist only inside
      the HAL and are generated spontaneously, as opposed to be related to
      a physical sensor.

      reporting-mode: n/a
  **/
  SENSOR_TYPE_META_DATA = 1;
  /** An calibreated accelerometer sensor reports the acceleration of
      the device along the three sensor axes.
      The measured acceleration includes both the physical acceleration
      (change of velocity) and the gravity.
      The measurement is reported in the x, y, and z fields of 
      SensorEventT.SensorUncalibratedEventT
      where bias value remains non-zero.

      All values are in SI units (m/s^2) and measure the acceleration
      of the device minus the force of gravity 
      along the three sensor axes.

      reporting-mode: continuous
  **/
  SENSOR_TYPE_ACCELEROMETER = 2;

  /** An calibrated gyroscope sensor reports the rate of rotation around 
      the sensor axes with applying bias compensation
      to them, along with a bias estimate.

      All values are in radians/second and are reported in the fields of
      SensorEventT.SensorUncalibratedEventT
      where bias values remains zero.

      reporting-mode: continuous
  **/
  SENSOR_TYPE_GYROSCOPE 	= 4;

  /** An uncalibrated gyroscope reports the rate of rotation around the
      sensor axes without applying bias compensation
      to them, along with a bias estimate.

      All values are in radians/second and are reported in the fields of
      SensorEventT.SensorUncalibratedEventT
      where bias values remains zero.

      reporting-mode: continuous
  **/
  SENSOR_TYPE_GYROSCOPE_UNCALIBRATED = 16;

  /** An uncalibreated accelerometer sensor reports the acceleration of
      the device along the three sensor axes.
      The measured acceleration includes both the physical acceleration
      (change of velocity) and the gravity.
      The measurement is reported in the x, y, and z fields of
      SensorEventT.SensorUncalibratedEventT
      while bias values zero

      All values are in SI units (m/s^2) and measure the acceleration
      of the device minus the force of gravity
      along the three sensor axes.

      reporting-mode: continuous
  **/
  SENSOR_TYPE_ACCELEROMETER_UNCALIBRATED = 35;

  /** heading sensor measures the direction in which the device is
      pointing relative to true north in degrees.
      The heading sensor includes two SensorEventT values represent 
      by SensorEventT.SensorHeadingEventT
      One for the measured device heading and one for the accuracy
      of the provided heading value.

      Heading values reported by this sensor must be
      between 0.0 (inclusive) and 360.0 (exclusive), 
      with 0 indicating north, 90 east, 180 south, and 270 west.

      reporting-mode: continuous
  **/
  SENSOR_TYPE_HEADING = 42 ;
}

enum SensorServiceStateMaskT {
  /** Sensor HAL Deamon unknown state **/
  SENSOR_SERVICE_STATE_MASK_UNKNOWN        = 0x00000000;
  /** Sensor HAL Deamon is ready to communicate **/
  SENSOR_SERVICE_STATE_MASK_READY          = 0x00000001;
}

message SensorInfoT {
  option (sdv.sdvsidl.description) = "Sensor Information";

  /** Version of the hardware part + driver. The value of this field
      must increase when the driver is updated in a way that changes the
      output of this sensor. This is important for fused sensors when the
      fusion algorithm is updated.
  **/
  int32  sensor_version = 1;
  
  /** Name of this sensor.
      All sensors of the same "type" must have a different "name".
  **/
  string name = 2 [(sdv.vsidl.variable_type_max_size) = 255];
  
  /** Vendor of the hardware part	**/
  string vendor = 3 [(sdv.vsidl.variable_type_max_size) = 255];
  
  /** Sensor ID that identifies this sensors. This is used to reference
      this sensor throughout the Sensor API.
  **/
  int32 sensor_id = 4;
  
  /** This sensor's type **/
  int32 type = 5 [(sdv.sdvsidl.bitmask_enum_link) = "SensorTypeT"];
  
  /** Max sampling rate supported by the sensor in HZ,
      client can’t request the samples more than this
  **/
  float max_sampling_rate = 6;

  /** Min batch count supported by the sensor,
      client can’t request the samples less than this
  **/
  int32 min_batch_count = 7;

  /** Max batch count supported by the sensor,
      client can’t request the samples more than this
  **/
  int32 max_batch_count = 8;
  
  /** ODR - output data rate, List of sampling rate supported
      by the sensor in HZ **/
  repeated float odr  = 9 [(sdv.vsidl.repeated_field_max_count) = 6];
  
  /** Smallest difference between two values reported by this sensor **/
  float resolution  = 10;

  /** Maximum range of this sensor's value in SI units **/
  float max_range = 11;
}

/**
    Heading event data
**/
message SensorHeadingEventT {
  float heading = 1;
  float accuracy = 2;
}

/**
    uncalibrated and calibrated accelerometer, gyroscope event data
**/
message SensorUncalibratedEventT {
  float x_uncalib = 1;
  float y_uncalib = 2;
  float z_uncalib = 3;
  float x_bias = 4;
  float y_bias = 5;
  float z_bias = 6;
}

/** sensor Imu data **/
message SensorImuEventT {
  /* sensor identifier */
  int32 sensor_id = 1;
  /* sensor type */
  int32 type = 2;
  /* time is in nanosecond */
  uint64 timestamp = 3;
  /* gptp time is in nanosecond */
  uint64 gptp_timestamp = 4;
  /* sensor Imu data */
  SensorUncalibratedEventT data = 5;
}

/** sensor heading data **/
message SensorHeadEventT {
  /* sensor identifier */
  int32 sensor_id = 1;
  /* sensor type */
  int32 type = 2;
  /* time is in nanosecond */
  uint64 timestamp = 3;
  /* gptp time is in nanosecond */
  uint64 gptp_timestamp = 4;
  /* sensor Imu data */
  SensorHeadingEventT data = 5;
}
