/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v0/com/qualcomm/qti/sensor/SensorInterfaceSomeIPProxy.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace com {
namespace qualcomm {
namespace qti {
namespace sensor {

std::shared_ptr<CommonAPI::SomeIP::Proxy> createSensorInterfaceSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection) {
    return std::make_shared< SensorInterfaceSomeIPProxy>(_address, _connection);
}

void initializeSensorInterfaceSomeIPProxy() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:com.qualcomm.qti.sensor.SensorInterface:v0_1:com.qualcomm.qti.sensor.SensorInterface",
        0xee01, 0x1, 0, 1);
    CommonAPI::SomeIP::Factory::get()->registerProxyCreateMethod(
        "com.qualcomm.qti.sensor.SensorInterface:v0_1",
        &createSensorInterfaceSomeIPProxy);
}

INITIALIZER(registerSensorInterfaceSomeIPProxy) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeSensorInterfaceSomeIPProxy);
}

SensorInterfaceSomeIPProxy::SensorInterfaceSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection)
        : CommonAPI::SomeIP::Proxy(_address, _connection),
          sensorCapabilities_(*this, 0x80e8, CommonAPI::SomeIP::event_id_t(0x80e9), CommonAPI::SomeIP::event_type_e::ET_EVENT , CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, std::make_tuple(&::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorCapabilitiesMaskDeployment)),
          sensorConfigUpdate_(*this, 0x80e8, CommonAPI::SomeIP::event_id_t(0x80ea), CommonAPI::SomeIP::event_type_e::ET_EVENT , CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr), static_cast< CommonAPI::EmptyDeployment* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr))),
          sensorDataRead_(*this, 0x80e8, CommonAPI::SomeIP::event_id_t(0x80eb), CommonAPI::SomeIP::event_type_e::ET_EVENT , CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, std::make_tuple(static_cast< CommonAPI::SomeIP::ArrayDeployment< ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorEventDeployment_t >* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr)))
{
}

SensorInterfaceSomeIPProxy::~SensorInterfaceSomeIPProxy() {
    completed_.set_value();
}


SensorInterfaceSomeIPProxy::SensorCapabilitiesEvent& SensorInterfaceSomeIPProxy::getSensorCapabilitiesEvent() {
    return sensorCapabilities_;
}
SensorInterfaceSomeIPProxy::SensorConfigUpdateEvent& SensorInterfaceSomeIPProxy::getSensorConfigUpdateEvent() {
    return sensorConfigUpdate_;
}
SensorInterfaceSomeIPProxy::SensorDataReadEvent& SensorInterfaceSomeIPProxy::getSensorDataReadEvent() {
    return sensorDataRead_;
}

void SensorInterfaceSomeIPProxy::RegisterSensorClient(CommonAPI::CallStatus &_internalCallStatus, SensorInterface::SensorResponse &_response, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< SensorInterface::SensorResponse, ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorResponseDeployment_t> deploy_response(&::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorResponseDeployment);
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                SensorInterface::SensorResponse,
                ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorResponseDeployment_t
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x7d01),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        _internalCallStatus,
        deploy_response);
    _response = deploy_response.getValue();
}

std::future<CommonAPI::CallStatus> SensorInterfaceSomeIPProxy::RegisterSensorClientAsync(RegisterSensorClientAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< SensorInterface::SensorResponse, ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorResponseDeployment_t> deploy_response(&::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorResponseDeployment);
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                SensorInterface::SensorResponse,
                ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorResponseDeployment_t
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x7d01),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< SensorInterface::SensorResponse, ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorResponseDeployment_t > _response) {
            if (_callback)
                _callback(_internalCallStatus, _response.getValue());
        },
        std::make_tuple(deploy_response));
}

void SensorInterfaceSomeIPProxy::DeRegisterSensorClient(CommonAPI::CallStatus &_internalCallStatus, SensorInterface::SensorResponse &_response, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< SensorInterface::SensorResponse, ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorResponseDeployment_t> deploy_response(&::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorResponseDeployment);
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                SensorInterface::SensorResponse,
                ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorResponseDeployment_t
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x7d02),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        _internalCallStatus,
        deploy_response);
    _response = deploy_response.getValue();
}

std::future<CommonAPI::CallStatus> SensorInterfaceSomeIPProxy::DeRegisterSensorClientAsync(DeRegisterSensorClientAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< SensorInterface::SensorResponse, ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorResponseDeployment_t> deploy_response(&::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorResponseDeployment);
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                SensorInterface::SensorResponse,
                ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorResponseDeployment_t
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x7d02),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< SensorInterface::SensorResponse, ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorResponseDeployment_t > _response) {
            if (_callback)
                _callback(_internalCallStatus, _response.getValue());
        },
        std::make_tuple(deploy_response));
}

void SensorInterfaceSomeIPProxy::GetSensorList(CommonAPI::CallStatus &_internalCallStatus, std::vector< SensorInterface::SensorList > &_sensor, int32_t &_count, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< std::vector< SensorInterface::SensorList >, CommonAPI::SomeIP::ArrayDeployment< ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorListDeployment_t >> deploy_sensor(static_cast< CommonAPI::SomeIP::ArrayDeployment< ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorListDeployment_t >* >(nullptr));
    CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t>> deploy_count(static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::vector< SensorInterface::SensorList >,
                CommonAPI::SomeIP::ArrayDeployment< ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorListDeployment_t >
            >,
            CommonAPI::Deployable<
                int32_t,
                CommonAPI::SomeIP::IntegerDeployment<int32_t>
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x7d03),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        _internalCallStatus,
        deploy_sensor, deploy_count);
    _sensor = deploy_sensor.getValue();
    _count = deploy_count.getValue();
}

std::future<CommonAPI::CallStatus> SensorInterfaceSomeIPProxy::GetSensorListAsync(GetSensorListAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< std::vector< SensorInterface::SensorList >, CommonAPI::SomeIP::ArrayDeployment< ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorListDeployment_t >> deploy_sensor(static_cast< CommonAPI::SomeIP::ArrayDeployment< ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorListDeployment_t >* >(nullptr));
    CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t>> deploy_count(static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::vector< SensorInterface::SensorList >,
                CommonAPI::SomeIP::ArrayDeployment< ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorListDeployment_t >
            >,
            CommonAPI::Deployable<
                int32_t,
                CommonAPI::SomeIP::IntegerDeployment<int32_t>
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x7d03),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< std::vector< SensorInterface::SensorList >, CommonAPI::SomeIP::ArrayDeployment< ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorListDeployment_t > > _sensor, CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t> > _count) {
            if (_callback)
                _callback(_internalCallStatus, _sensor.getValue(), _count.getValue());
        },
        std::make_tuple(deploy_sensor, deploy_count));
}

void SensorInterfaceSomeIPProxy::SensorConfig(int32_t _sensorId, float _samplingRate, int32_t _batchCount, CommonAPI::CallStatus &_internalCallStatus, SensorInterface::SensorResponse &_response, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t>> deploy_sensorId(_sensorId, static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr));
    CommonAPI::Deployable< float, CommonAPI::EmptyDeployment> deploy_samplingRate(_samplingRate, static_cast< CommonAPI::EmptyDeployment* >(nullptr));
    CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t>> deploy_batchCount(_batchCount, static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr));
    CommonAPI::Deployable< SensorInterface::SensorResponse, ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorResponseDeployment_t> deploy_response(&::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorResponseDeployment);
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                int32_t,
                CommonAPI::SomeIP::IntegerDeployment<int32_t>
            >,
            CommonAPI::Deployable<
                float,
                CommonAPI::EmptyDeployment
            >,
            CommonAPI::Deployable<
                int32_t,
                CommonAPI::SomeIP::IntegerDeployment<int32_t>
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                SensorInterface::SensorResponse,
                ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorResponseDeployment_t
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x7d04),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_sensorId, deploy_samplingRate, deploy_batchCount,
        _internalCallStatus,
        deploy_response);
    _response = deploy_response.getValue();
}

std::future<CommonAPI::CallStatus> SensorInterfaceSomeIPProxy::SensorConfigAsync(const int32_t &_sensorId, const float &_samplingRate, const int32_t &_batchCount, SensorConfigAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t>> deploy_sensorId(_sensorId, static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr));
    CommonAPI::Deployable< float, CommonAPI::EmptyDeployment> deploy_samplingRate(_samplingRate, static_cast< CommonAPI::EmptyDeployment* >(nullptr));
    CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t>> deploy_batchCount(_batchCount, static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr));
    CommonAPI::Deployable< SensorInterface::SensorResponse, ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorResponseDeployment_t> deploy_response(&::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorResponseDeployment);
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                int32_t,
                CommonAPI::SomeIP::IntegerDeployment<int32_t>
            >,
            CommonAPI::Deployable<
                float,
                CommonAPI::EmptyDeployment
            >,
            CommonAPI::Deployable<
                int32_t,
                CommonAPI::SomeIP::IntegerDeployment<int32_t>
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                SensorInterface::SensorResponse,
                ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorResponseDeployment_t
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x7d04),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_sensorId, deploy_samplingRate, deploy_batchCount,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< SensorInterface::SensorResponse, ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorResponseDeployment_t > _response) {
            if (_callback)
                _callback(_internalCallStatus, _response.getValue());
        },
        std::make_tuple(deploy_response));
}

void SensorInterfaceSomeIPProxy::SensorControl(int32_t _sensorId, SensorInterface::SensorState _sensorState, CommonAPI::CallStatus &_internalCallStatus, SensorInterface::SensorResponse &_response, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t>> deploy_sensorId(_sensorId, static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr));
    CommonAPI::Deployable< SensorInterface::SensorState, ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorStateDeployment_t> deploy_sensorState(_sensorState, &::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorStateDeployment);
    CommonAPI::Deployable< SensorInterface::SensorResponse, ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorResponseDeployment_t> deploy_response(&::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorResponseDeployment);
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                int32_t,
                CommonAPI::SomeIP::IntegerDeployment<int32_t>
            >,
            CommonAPI::Deployable<
                SensorInterface::SensorState,
                ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorStateDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                SensorInterface::SensorResponse,
                ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorResponseDeployment_t
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x7d05),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_sensorId, deploy_sensorState,
        _internalCallStatus,
        deploy_response);
    _response = deploy_response.getValue();
}

std::future<CommonAPI::CallStatus> SensorInterfaceSomeIPProxy::SensorControlAsync(const int32_t &_sensorId, const SensorInterface::SensorState &_sensorState, SensorControlAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t>> deploy_sensorId(_sensorId, static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr));
    CommonAPI::Deployable< SensorInterface::SensorState, ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorStateDeployment_t> deploy_sensorState(_sensorState, &::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorStateDeployment);
    CommonAPI::Deployable< SensorInterface::SensorResponse, ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorResponseDeployment_t> deploy_response(&::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorResponseDeployment);
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                int32_t,
                CommonAPI::SomeIP::IntegerDeployment<int32_t>
            >,
            CommonAPI::Deployable<
                SensorInterface::SensorState,
                ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorStateDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                SensorInterface::SensorResponse,
                ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorResponseDeployment_t
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x7d05),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_sensorId, deploy_sensorState,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< SensorInterface::SensorResponse, ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorResponseDeployment_t > _response) {
            if (_callback)
                _callback(_internalCallStatus, _response.getValue());
        },
        std::make_tuple(deploy_response));
}

void SensorInterfaceSomeIPProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
    ownVersionMajor = 0;
    ownVersionMinor = 1;
}

std::future<void> SensorInterfaceSomeIPProxy::getCompletionFuture() {
    return completed_.get_future();
}

} // namespace sensor
} // namespace qti
} // namespace qualcomm
} // namespace com
} // namespace v0
