/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_COM_QUALCOMM_QTI_SENSOR_Sensor_Interface_PROXY_BASE_HPP_
#define V0_COM_QUALCOMM_QTI_SENSOR_Sensor_Interface_PROXY_BASE_HPP_

#include <v0/com/qualcomm/qti/sensor/SensorInterface.hpp>



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <cstdint>
#include <string>
#include <vector>

#include <CommonAPI/Event.hpp>
#include <CommonAPI/Proxy.hpp>
#include <functional>
#include <future>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace com {
namespace qualcomm {
namespace qti {
namespace sensor {

class SensorInterfaceProxyBase
    : virtual public CommonAPI::Proxy {
public:
    typedef CommonAPI::Event<
        ::v0::com::qualcomm::qti::sensor::SensorInterface::SensorCapabilitiesMask
    > SensorCapabilitiesEvent;
    typedef CommonAPI::Event<
        int32_t, float, int32_t
    > SensorConfigUpdateEvent;
    typedef CommonAPI::Event<
        std::vector< ::v0::com::qualcomm::qti::sensor::SensorInterface::SensorEvent >, int32_t
    > SensorDataReadEvent;

    typedef std::function<void(const CommonAPI::CallStatus&, const SensorInterface::SensorResponse&)> RegisterSensorClientAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const SensorInterface::SensorResponse&)> DeRegisterSensorClientAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const std::vector< SensorInterface::SensorList >&, const int32_t&)> GetSensorListAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const SensorInterface::SensorResponse&)> SensorConfigAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const SensorInterface::SensorResponse&)> SensorControlAsyncCallback;

    virtual SensorCapabilitiesEvent& getSensorCapabilitiesEvent() = 0;
    virtual SensorConfigUpdateEvent& getSensorConfigUpdateEvent() = 0;
    virtual SensorDataReadEvent& getSensorDataReadEvent() = 0;
    virtual void RegisterSensorClient(CommonAPI::CallStatus &_internalCallStatus, SensorInterface::SensorResponse &_response, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> RegisterSensorClientAsync(RegisterSensorClientAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual void DeRegisterSensorClient(CommonAPI::CallStatus &_internalCallStatus, SensorInterface::SensorResponse &_response, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> DeRegisterSensorClientAsync(DeRegisterSensorClientAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual void GetSensorList(CommonAPI::CallStatus &_internalCallStatus, std::vector< SensorInterface::SensorList > &_sensor, int32_t &_count, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> GetSensorListAsync(GetSensorListAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual void SensorConfig(int32_t _sensorId, float _samplingRate, int32_t _batchCount, CommonAPI::CallStatus &_internalCallStatus, SensorInterface::SensorResponse &_response, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> SensorConfigAsync(const int32_t &_sensorId, const float &_samplingRate, const int32_t &_batchCount, SensorConfigAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual void SensorControl(int32_t _sensorId, SensorInterface::SensorState _sensorState, CommonAPI::CallStatus &_internalCallStatus, SensorInterface::SensorResponse &_response, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> SensorControlAsync(const int32_t &_sensorId, const SensorInterface::SensorState &_sensorState, SensorControlAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;

    virtual std::future<void> getCompletionFuture() = 0;
};

} // namespace sensor
} // namespace qti
} // namespace qualcomm
} // namespace com
} // namespace v0


// Compatibility
namespace v0_1 = v0;

#endif // V0_COM_QUALCOMM_QTI_SENSOR_Sensor_Interface_PROXY_BASE_HPP_
