/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COM_QUALCOMM_QTI_SENSOR_Sensor_Interface_PROXY_HPP_
#define V1_COM_QUALCOMM_QTI_SENSOR_Sensor_Interface_PROXY_HPP_

#include <v1/com/qualcomm/qti/sensor/SensorInterfaceProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif


#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace com {
namespace qualcomm {
namespace qti {
namespace sensor {

template <typename ... _AttributeExtensions>
class SensorInterfaceProxy
    : virtual public SensorInterface,
      virtual public SensorInterfaceProxyBase,
      virtual public _AttributeExtensions... {
public:
    SensorInterfaceProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~SensorInterfaceProxy();

    typedef SensorInterface InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * Returns the wrapper class that provides access to the broadcast SensorCapabilities.
     */
    virtual SensorCapabilitiesEvent& getSensorCapabilitiesEvent() {
        return delegate_->getSensorCapabilitiesEvent();
    }
    /**
     * Returns the wrapper class that provides access to the broadcast SensorConfigUpdate.
     */
    virtual SensorConfigUpdateEvent& getSensorConfigUpdateEvent() {
        return delegate_->getSensorConfigUpdateEvent();
    }
    /**
     * Returns the wrapper class that provides access to the broadcast SensorImuDataRead.
     */
    virtual SensorImuDataReadEvent& getSensorImuDataReadEvent() {
        return delegate_->getSensorImuDataReadEvent();
    }
    /**
     * Returns the wrapper class that provides access to the broadcast SensorHeadingDataRead.
     */
    virtual SensorHeadingDataReadEvent& getSensorHeadingDataReadEvent() {
        return delegate_->getSensorHeadingDataReadEvent();
    }
    /**
     * Calls RegisterSensorClientReq with synchronous semantics.
     *
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void RegisterSensorClientReq(CommonAPI::CallStatus &_internalCallStatus, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT &_SensorResponse, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls RegisterSensorClientReq with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> RegisterSensorClientReqAsync(RegisterSensorClientReqAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls DeRegisterSensorClientReq with synchronous semantics.
     *
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void DeRegisterSensorClientReq(CommonAPI::CallStatus &_internalCallStatus, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT &_SensorResponse, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls DeRegisterSensorClientReq with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> DeRegisterSensorClientReqAsync(DeRegisterSensorClientReqAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls GetSensorListReq with synchronous semantics.
     *
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void GetSensorListReq(CommonAPI::CallStatus &_internalCallStatus, std::vector< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorInfoT > &_SensorList, int32_t &_count, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls GetSensorListReq with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> GetSensorListReqAsync(GetSensorListReqAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls SensorConfigReq with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void SensorConfigReq(int32_t _sensorId, float _samplingRate, int32_t _batchCount, CommonAPI::CallStatus &_internalCallStatus, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT &_SensorResponse, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls SensorConfigReq with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> SensorConfigReqAsync(const int32_t &_sensorId, const float &_samplingRate, const int32_t &_batchCount, SensorConfigReqAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls SensorControlReq with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void SensorControlReq(int32_t _sensorId, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorStateT _sensorState, CommonAPI::CallStatus &_internalCallStatus, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT &_SensorResponse, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls SensorControlReq with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> SensorControlReqAsync(const int32_t &_sensorId, const ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorStateT &_sensorState, SensorControlReqAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);



 private:
    std::shared_ptr< SensorInterfaceProxyBase> delegate_;
};

typedef SensorInterfaceProxy<> SensorInterfaceProxyDefault;


//
// SensorInterfaceProxy Implementation
//
template <typename ... _AttributeExtensions>
SensorInterfaceProxy<_AttributeExtensions...>::SensorInterfaceProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< SensorInterfaceProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< SensorInterfaceProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
SensorInterfaceProxy<_AttributeExtensions...>::~SensorInterfaceProxy() {
}

template <typename ... _AttributeExtensions>
void SensorInterfaceProxy<_AttributeExtensions...>::RegisterSensorClientReq(CommonAPI::CallStatus &_internalCallStatus, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT &_SensorResponse, const CommonAPI::CallInfo *_info) {
    delegate_->RegisterSensorClientReq(_internalCallStatus, _SensorResponse, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> SensorInterfaceProxy<_AttributeExtensions...>::RegisterSensorClientReqAsync(RegisterSensorClientReqAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->RegisterSensorClientReqAsync(_callback, _info);
}
template <typename ... _AttributeExtensions>
void SensorInterfaceProxy<_AttributeExtensions...>::DeRegisterSensorClientReq(CommonAPI::CallStatus &_internalCallStatus, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT &_SensorResponse, const CommonAPI::CallInfo *_info) {
    delegate_->DeRegisterSensorClientReq(_internalCallStatus, _SensorResponse, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> SensorInterfaceProxy<_AttributeExtensions...>::DeRegisterSensorClientReqAsync(DeRegisterSensorClientReqAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->DeRegisterSensorClientReqAsync(_callback, _info);
}
template <typename ... _AttributeExtensions>
void SensorInterfaceProxy<_AttributeExtensions...>::GetSensorListReq(CommonAPI::CallStatus &_internalCallStatus, std::vector< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorInfoT > &_SensorList, int32_t &_count, const CommonAPI::CallInfo *_info) {
    delegate_->GetSensorListReq(_internalCallStatus, _SensorList, _count, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> SensorInterfaceProxy<_AttributeExtensions...>::GetSensorListReqAsync(GetSensorListReqAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->GetSensorListReqAsync(_callback, _info);
}
template <typename ... _AttributeExtensions>
void SensorInterfaceProxy<_AttributeExtensions...>::SensorConfigReq(int32_t _sensorId, float _samplingRate, int32_t _batchCount, CommonAPI::CallStatus &_internalCallStatus, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT &_SensorResponse, const CommonAPI::CallInfo *_info) {
    delegate_->SensorConfigReq(_sensorId, _samplingRate, _batchCount, _internalCallStatus, _SensorResponse, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> SensorInterfaceProxy<_AttributeExtensions...>::SensorConfigReqAsync(const int32_t &_sensorId, const float &_samplingRate, const int32_t &_batchCount, SensorConfigReqAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->SensorConfigReqAsync(_sensorId, _samplingRate, _batchCount, _callback, _info);
}
template <typename ... _AttributeExtensions>
void SensorInterfaceProxy<_AttributeExtensions...>::SensorControlReq(int32_t _sensorId, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorStateT _sensorState, CommonAPI::CallStatus &_internalCallStatus, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT &_SensorResponse, const CommonAPI::CallInfo *_info) {
    if (!_sensorState.validate()) {
        _internalCallStatus = CommonAPI::CallStatus::INVALID_VALUE;
        return;
    }
    delegate_->SensorControlReq(_sensorId, _sensorState, _internalCallStatus, _SensorResponse, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> SensorInterfaceProxy<_AttributeExtensions...>::SensorControlReqAsync(const int32_t &_sensorId, const ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorStateT &_sensorState, SensorControlReqAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    if (!_sensorState.validate()) {
        ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT SensorResponse = ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT::SENSOR_RETURN_UNKNOWN;
        _callback(CommonAPI::CallStatus::INVALID_VALUE, SensorResponse);
        std::promise<CommonAPI::CallStatus> promise;
        promise.set_value(CommonAPI::CallStatus::INVALID_VALUE);
        return promise.get_future();
    }
    return delegate_->SensorControlReqAsync(_sensorId, _sensorState, _callback, _info);
}

template <typename ... _AttributeExtensions>
const CommonAPI::Address &SensorInterfaceProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool SensorInterfaceProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool SensorInterfaceProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& SensorInterfaceProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& SensorInterfaceProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> SensorInterfaceProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace sensor
} // namespace qti
} // namespace qualcomm
} // namespace com
} // namespace v1



// Compatibility
namespace v1_0 = v1;

#endif // V1_COM_QUALCOMM_QTI_SENSOR_Sensor_Interface_PROXY_HPP_
