/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COM_QUALCOMM_QTI_SENSOR_Sensor_Interface_STUB_HPP_
#define V1_COM_QUALCOMM_QTI_SENSOR_Sensor_Interface_STUB_HPP_

#include <functional>
#include <sstream>



#include <v1/com/qualcomm/qti/sensor/SensorInterfaceTypes.hpp>

#include <v1/com/qualcomm/qti/sensor/SensorInterface.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <cstdint>
#include <string>
#include <unordered_set>
#include <vector>


#include <CommonAPI/Stub.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace com {
namespace qualcomm {
namespace qti {
namespace sensor {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service SensorInterface. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class SensorInterfaceStubAdapter
    : public virtual CommonAPI::StubAdapter,
      public virtual SensorInterface {
 public:
    /**
    * Sends a broadcast event for SensorCapabilities. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireSensorCapabilitiesEvent(const ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorServiceStateMaskT &_SensorCapabilitiesMask) = 0;
    /**
    * Sends a broadcast event for SensorConfigUpdate. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireSensorConfigUpdateEvent(const int32_t &_sensorId, const float &_samplingRate, const int32_t &_batchCount) = 0;
    /**
    * Sends a broadcast event for SensorImuDataRead. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireSensorImuDataReadEvent(const std::vector< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorImuEventT > &_SensorImuEvent, const int32_t &_count) = 0;
    /**
    * Sends a broadcast event for SensorHeadingDataRead. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireSensorHeadingDataReadEvent(const std::vector< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorHeadEventT > &_sensorHeadEvent, const int32_t &_count) = 0;


    virtual void deactivateManagedInstances() = 0;


protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */

};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for SensorInterface.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class SensorInterfaceStubRemoteEvent
{
public:
    virtual ~SensorInterfaceStubRemoteEvent() { }

};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service SensorInterface to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class SensorInterfaceStub
    : public virtual CommonAPI::Stub<SensorInterfaceStubAdapter, SensorInterfaceStubRemoteEvent>
{
public:
    typedef std::function<void (::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT _SensorResponse)> RegisterSensorClientReqReply_t;
    typedef std::function<void (::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT _SensorResponse)> DeRegisterSensorClientReqReply_t;
    typedef std::function<void (std::vector< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorInfoT > _SensorList, int32_t _count)> GetSensorListReqReply_t;
    typedef std::function<void (::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT _SensorResponse)> SensorConfigReqReply_t;
    typedef std::function<void (::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT _SensorResponse)> SensorControlReqReply_t;

    virtual ~SensorInterfaceStub() {}
    void lockInterfaceVersionAttribute(bool _lockAccess) { static_cast<void>(_lockAccess); }
    bool hasElement(const uint32_t _id) const {
        return (_id < 9);
    }
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) = 0;

    /// Sends a broadcast event for SensorCapabilities.
    virtual void fireSensorCapabilitiesEvent(const ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorServiceStateMaskT &_SensorCapabilitiesMask) {
        auto stubAdapter = CommonAPI::Stub<SensorInterfaceStubAdapter, SensorInterfaceStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireSensorCapabilitiesEvent(_SensorCapabilitiesMask);
    }
    /// Sends a broadcast event for SensorConfigUpdate.
    virtual void fireSensorConfigUpdateEvent(const int32_t &_sensorId, const float &_samplingRate, const int32_t &_batchCount) {
        auto stubAdapter = CommonAPI::Stub<SensorInterfaceStubAdapter, SensorInterfaceStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireSensorConfigUpdateEvent(_sensorId, _samplingRate, _batchCount);
    }
    /// Sends a broadcast event for SensorImuDataRead.
    virtual void fireSensorImuDataReadEvent(const std::vector< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorImuEventT > &_SensorImuEvent, const int32_t &_count) {
        auto stubAdapter = CommonAPI::Stub<SensorInterfaceStubAdapter, SensorInterfaceStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireSensorImuDataReadEvent(_SensorImuEvent, _count);
    }
    /// Sends a broadcast event for SensorHeadingDataRead.
    virtual void fireSensorHeadingDataReadEvent(const std::vector< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorHeadEventT > &_sensorHeadEvent, const int32_t &_count) {
        auto stubAdapter = CommonAPI::Stub<SensorInterfaceStubAdapter, SensorInterfaceStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireSensorHeadingDataReadEvent(_sensorHeadEvent, _count);
    }
    /// This is the method that will be called on remote calls on the method RegisterSensorClientReq.
    virtual void RegisterSensorClientReq(const std::shared_ptr<CommonAPI::ClientId> _client, RegisterSensorClientReqReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method DeRegisterSensorClientReq.
    virtual void DeRegisterSensorClientReq(const std::shared_ptr<CommonAPI::ClientId> _client, DeRegisterSensorClientReqReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method GetSensorListReq.
    virtual void GetSensorListReq(const std::shared_ptr<CommonAPI::ClientId> _client, GetSensorListReqReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method SensorConfigReq.
    virtual void SensorConfigReq(const std::shared_ptr<CommonAPI::ClientId> _client, int32_t _sensorId, float _samplingRate, int32_t _batchCount, SensorConfigReqReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method SensorControlReq.
    virtual void SensorControlReq(const std::shared_ptr<CommonAPI::ClientId> _client, int32_t _sensorId, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorStateT _sensorState, SensorControlReqReply_t _reply) = 0;


    using CommonAPI::Stub<SensorInterfaceStubAdapter, SensorInterfaceStubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<SensorInterfaceStubAdapter, SensorInterfaceStubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<SensorInterfaceStubAdapter, SensorInterfaceStubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef SensorInterfaceStubRemoteEvent RemoteEventType;
    typedef SensorInterface StubInterface;
};

} // namespace sensor
} // namespace qti
} // namespace qualcomm
} // namespace com
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_COM_QUALCOMM_QTI_SENSOR_Sensor_Interface_STUB_HPP_
