/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COM_QUALCOMM_QTI_SENSOR_Sensor_Interface_STUB_DEFAULT_HPP_
#define V1_COM_QUALCOMM_QTI_SENSOR_Sensor_Interface_STUB_DEFAULT_HPP_


#include <CommonAPI/Export.hpp>

#include <v1/com/qualcomm/qti/sensor/SensorInterfaceStub.hpp>
#include <cassert>
#include <sstream>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v1 {
namespace com {
namespace qualcomm {
namespace qti {
namespace sensor {

/**
 * Provides a default implementation for SensorInterfaceStubRemoteEvent and
 * SensorInterfaceStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class COMMONAPI_EXPORT_CLASS_EXPLICIT SensorInterfaceStubDefault
    : public virtual SensorInterfaceStub {
public:
    COMMONAPI_EXPORT SensorInterfaceStubDefault()
        : remoteEventHandler_(this),
          interfaceVersion_(SensorInterface::getInterfaceVersion()) {
    }

    COMMONAPI_EXPORT const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return interfaceVersion_;
    }

    COMMONAPI_EXPORT SensorInterfaceStubRemoteEvent* initStubAdapter(const std::shared_ptr< SensorInterfaceStubAdapter> &_adapter) {
        CommonAPI::Stub<SensorInterfaceStubAdapter, SensorInterfaceStubRemoteEvent>::stubAdapter_ = _adapter;
        return &remoteEventHandler_;
    }

    COMMONAPI_EXPORT virtual void fireSensorCapabilitiesEvent(const ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorServiceStateMaskT &_SensorCapabilitiesMask) {
        if (!_SensorCapabilitiesMask.validate()) {
            return;
        }
        SensorInterfaceStub::fireSensorCapabilitiesEvent(_SensorCapabilitiesMask);
    }
    COMMONAPI_EXPORT virtual void fireSensorConfigUpdateEvent(const int32_t &_sensorId, const float &_samplingRate, const int32_t &_batchCount) {
        SensorInterfaceStub::fireSensorConfigUpdateEvent(_sensorId, _samplingRate, _batchCount);
    }
    COMMONAPI_EXPORT virtual void fireSensorImuDataReadEvent(const std::vector< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorImuEventT > &_SensorImuEvent, const int32_t &_count) {
        SensorInterfaceStub::fireSensorImuDataReadEvent(_SensorImuEvent, _count);
    }
    COMMONAPI_EXPORT virtual void fireSensorHeadingDataReadEvent(const std::vector< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorHeadEventT > &_sensorHeadEvent, const int32_t &_count) {
        SensorInterfaceStub::fireSensorHeadingDataReadEvent(_sensorHeadEvent, _count);
    }
    COMMONAPI_EXPORT virtual void RegisterSensorClientReq(const std::shared_ptr<CommonAPI::ClientId> _client, RegisterSensorClientReqReply_t _reply) {
        (void)_client;
        ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT SensorResponse = ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT::SENSOR_RETURN_UNKNOWN;
        if (!SensorResponse.validate()) {
            return;
        }
        _reply(SensorResponse);
    }
    COMMONAPI_EXPORT virtual void DeRegisterSensorClientReq(const std::shared_ptr<CommonAPI::ClientId> _client, DeRegisterSensorClientReqReply_t _reply) {
        (void)_client;
        ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT SensorResponse = ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT::SENSOR_RETURN_UNKNOWN;
        if (!SensorResponse.validate()) {
            return;
        }
        _reply(SensorResponse);
    }
    COMMONAPI_EXPORT virtual void GetSensorListReq(const std::shared_ptr<CommonAPI::ClientId> _client, GetSensorListReqReply_t _reply) {
        (void)_client;
        std::vector< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorInfoT > SensorList = {};
        int32_t count = 0;
        _reply(SensorList, count);
    }
    COMMONAPI_EXPORT virtual void SensorConfigReq(const std::shared_ptr<CommonAPI::ClientId> _client, int32_t _sensorId, float _samplingRate, int32_t _batchCount, SensorConfigReqReply_t _reply) {
        (void)_client;
        (void)_sensorId;
        (void)_samplingRate;
        (void)_batchCount;
        ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT SensorResponse = ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT::SENSOR_RETURN_UNKNOWN;
        if (!SensorResponse.validate()) {
            return;
        }
        _reply(SensorResponse);
    }
    COMMONAPI_EXPORT virtual void SensorControlReq(const std::shared_ptr<CommonAPI::ClientId> _client, int32_t _sensorId, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorStateT _sensorState, SensorControlReqReply_t _reply) {
        (void)_client;
        (void)_sensorId;
        (void)_sensorState;
        ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT SensorResponse = ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT::SENSOR_RETURN_UNKNOWN;
        if (!SensorResponse.validate()) {
            return;
        }
        _reply(SensorResponse);
    }


protected:
    class COMMONAPI_EXPORT_CLASS_EXPLICIT RemoteEventHandler: public virtual SensorInterfaceStubRemoteEvent {
    public:
        COMMONAPI_EXPORT RemoteEventHandler(SensorInterfaceStubDefault *_defaultStub)
            : 
              defaultStub_(_defaultStub) {
        }


    private:
        SensorInterfaceStubDefault *defaultStub_;
    };
protected:
    SensorInterfaceStubDefault::RemoteEventHandler remoteEventHandler_;

private:


    CommonAPI::Version interfaceVersion_;
};

} // namespace sensor
} // namespace qti
} // namespace qualcomm
} // namespace com
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_COM_QUALCOMM_QTI_SENSOR_Sensor_Interface_STUB_DEFAULT
