/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V0_COM_QUALCOMM_QTI_SENSOR_SENSOR_INTERFACE_SOMEIP_PROXY_HPP_
#define V0_COM_QUALCOMM_QTI_SENSOR_SENSOR_INTERFACE_SOMEIP_PROXY_HPP_

#include <v0/com/qualcomm/qti/sensor/SensorInterfaceProxyBase.hpp>
#include <v0/com/qualcomm/qti/sensor/SensorInterfaceSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Proxy.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Event.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <string>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v0 {
namespace com {
namespace qualcomm {
namespace qti {
namespace sensor {

class SensorInterfaceSomeIPProxy
    : virtual public SensorInterfaceProxyBase,
      virtual public CommonAPI::SomeIP::Proxy {
public:
    SensorInterfaceSomeIPProxy(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection);

    virtual ~SensorInterfaceSomeIPProxy();

    virtual SensorCapabilitiesEvent& getSensorCapabilitiesEvent();

    virtual SensorConfigUpdateEvent& getSensorConfigUpdateEvent();

    virtual SensorDataReadEvent& getSensorDataReadEvent();

    virtual void RegisterSensorClient(CommonAPI::CallStatus &_internalCallStatus, SensorInterface::SensorResponse &_response, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> RegisterSensorClientAsync(RegisterSensorClientAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    virtual void DeRegisterSensorClient(CommonAPI::CallStatus &_internalCallStatus, SensorInterface::SensorResponse &_response, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> DeRegisterSensorClientAsync(DeRegisterSensorClientAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    virtual void GetSensorList(CommonAPI::CallStatus &_internalCallStatus, std::vector< SensorInterface::SensorList > &_sensor, int32_t &_count, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> GetSensorListAsync(GetSensorListAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    virtual void SensorConfig(int32_t _sensorId, float _samplingRate, int32_t _batchCount, CommonAPI::CallStatus &_internalCallStatus, SensorInterface::SensorResponse &_response, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> SensorConfigAsync(const int32_t &_sensorId, const float &_samplingRate, const int32_t &_batchCount, SensorConfigAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    virtual void SensorControl(int32_t _sensorId, SensorInterface::SensorState _sensorState, CommonAPI::CallStatus &_internalCallStatus, SensorInterface::SensorResponse &_response, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> SensorControlAsync(const int32_t &_sensorId, const SensorInterface::SensorState &_sensorState, SensorControlAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    virtual void getOwnVersion(uint16_t &_major, uint16_t &_minor) const;

    virtual std::future<void> getCompletionFuture();

private:
    CommonAPI::SomeIP::Event<SensorCapabilitiesEvent, CommonAPI::Deployable< ::v0::com::qualcomm::qti::sensor::SensorInterface::SensorCapabilitiesMask, ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorCapabilitiesMaskDeployment_t >> sensorCapabilities_;
    CommonAPI::SomeIP::Event<SensorConfigUpdateEvent, CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t> >, CommonAPI::Deployable< float, CommonAPI::EmptyDeployment >, CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t> >> sensorConfigUpdate_;
    CommonAPI::SomeIP::Event<SensorDataReadEvent, CommonAPI::Deployable< std::vector< ::v0::com::qualcomm::qti::sensor::SensorInterface::SensorEvent >, CommonAPI::SomeIP::ArrayDeployment< ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorEventDeployment_t > >, CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t> >> sensorDataRead_;

    std::promise<void> completed_;
};

} // namespace sensor
} // namespace qti
} // namespace qualcomm
} // namespace com
} // namespace v0

#endif // V0_COM_QUALCOMM_QTI_SENSOR_Sensor_Interface_SOMEIP_PROXY_HPP_
