/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_COM_QUALCOMM_QTI_SENSOR_Sensor_Interface_PROXY_HPP_
#define V0_COM_QUALCOMM_QTI_SENSOR_Sensor_Interface_PROXY_HPP_

#include <v0/com/qualcomm/qti/sensor/SensorInterfaceProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif


#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace com {
namespace qualcomm {
namespace qti {
namespace sensor {

template <typename ... _AttributeExtensions>
class SensorInterfaceProxy
    : virtual public SensorInterface,
      virtual public SensorInterfaceProxyBase,
      virtual public _AttributeExtensions... {
public:
    SensorInterfaceProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~SensorInterfaceProxy();

    typedef SensorInterface InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * Returns the wrapper class that provides access to the broadcast SensorCapabilities.
     */
    virtual SensorCapabilitiesEvent& getSensorCapabilitiesEvent() {
        return delegate_->getSensorCapabilitiesEvent();
    }
    /**
     * Returns the wrapper class that provides access to the broadcast SensorConfigUpdate.
     */
    virtual SensorConfigUpdateEvent& getSensorConfigUpdateEvent() {
        return delegate_->getSensorConfigUpdateEvent();
    }
    /**
     * Returns the wrapper class that provides access to the broadcast SensorDataRead.
     */
    virtual SensorDataReadEvent& getSensorDataReadEvent() {
        return delegate_->getSensorDataReadEvent();
    }
    /**
     * Calls RegisterSensorClient with synchronous semantics.
     *
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void RegisterSensorClient(CommonAPI::CallStatus &_internalCallStatus, SensorInterface::SensorResponse &_response, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls RegisterSensorClient with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> RegisterSensorClientAsync(RegisterSensorClientAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls DeRegisterSensorClient with synchronous semantics.
     *
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void DeRegisterSensorClient(CommonAPI::CallStatus &_internalCallStatus, SensorInterface::SensorResponse &_response, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls DeRegisterSensorClient with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> DeRegisterSensorClientAsync(DeRegisterSensorClientAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls GetSensorList with synchronous semantics.
     *
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void GetSensorList(CommonAPI::CallStatus &_internalCallStatus, std::vector< SensorInterface::SensorList > &_sensor, int32_t &_count, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls GetSensorList with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> GetSensorListAsync(GetSensorListAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls SensorConfig with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void SensorConfig(int32_t _sensorId, float _samplingRate, int32_t _batchCount, CommonAPI::CallStatus &_internalCallStatus, SensorInterface::SensorResponse &_response, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls SensorConfig with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> SensorConfigAsync(const int32_t &_sensorId, const float &_samplingRate, const int32_t &_batchCount, SensorConfigAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls SensorControl with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void SensorControl(int32_t _sensorId, SensorInterface::SensorState _sensorState, CommonAPI::CallStatus &_internalCallStatus, SensorInterface::SensorResponse &_response, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls SensorControl with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> SensorControlAsync(const int32_t &_sensorId, const SensorInterface::SensorState &_sensorState, SensorControlAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);



 private:
    std::shared_ptr< SensorInterfaceProxyBase> delegate_;
};

typedef SensorInterfaceProxy<> SensorInterfaceProxyDefault;


//
// SensorInterfaceProxy Implementation
//
template <typename ... _AttributeExtensions>
SensorInterfaceProxy<_AttributeExtensions...>::SensorInterfaceProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< SensorInterfaceProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< SensorInterfaceProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
SensorInterfaceProxy<_AttributeExtensions...>::~SensorInterfaceProxy() {
}

template <typename ... _AttributeExtensions>
void SensorInterfaceProxy<_AttributeExtensions...>::RegisterSensorClient(CommonAPI::CallStatus &_internalCallStatus, SensorInterface::SensorResponse &_response, const CommonAPI::CallInfo *_info) {
    delegate_->RegisterSensorClient(_internalCallStatus, _response, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> SensorInterfaceProxy<_AttributeExtensions...>::RegisterSensorClientAsync(RegisterSensorClientAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->RegisterSensorClientAsync(_callback, _info);
}
template <typename ... _AttributeExtensions>
void SensorInterfaceProxy<_AttributeExtensions...>::DeRegisterSensorClient(CommonAPI::CallStatus &_internalCallStatus, SensorInterface::SensorResponse &_response, const CommonAPI::CallInfo *_info) {
    delegate_->DeRegisterSensorClient(_internalCallStatus, _response, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> SensorInterfaceProxy<_AttributeExtensions...>::DeRegisterSensorClientAsync(DeRegisterSensorClientAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->DeRegisterSensorClientAsync(_callback, _info);
}
template <typename ... _AttributeExtensions>
void SensorInterfaceProxy<_AttributeExtensions...>::GetSensorList(CommonAPI::CallStatus &_internalCallStatus, std::vector< SensorInterface::SensorList > &_sensor, int32_t &_count, const CommonAPI::CallInfo *_info) {
    delegate_->GetSensorList(_internalCallStatus, _sensor, _count, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> SensorInterfaceProxy<_AttributeExtensions...>::GetSensorListAsync(GetSensorListAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->GetSensorListAsync(_callback, _info);
}
template <typename ... _AttributeExtensions>
void SensorInterfaceProxy<_AttributeExtensions...>::SensorConfig(int32_t _sensorId, float _samplingRate, int32_t _batchCount, CommonAPI::CallStatus &_internalCallStatus, SensorInterface::SensorResponse &_response, const CommonAPI::CallInfo *_info) {
    delegate_->SensorConfig(_sensorId, _samplingRate, _batchCount, _internalCallStatus, _response, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> SensorInterfaceProxy<_AttributeExtensions...>::SensorConfigAsync(const int32_t &_sensorId, const float &_samplingRate, const int32_t &_batchCount, SensorConfigAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->SensorConfigAsync(_sensorId, _samplingRate, _batchCount, _callback, _info);
}
template <typename ... _AttributeExtensions>
void SensorInterfaceProxy<_AttributeExtensions...>::SensorControl(int32_t _sensorId, SensorInterface::SensorState _sensorState, CommonAPI::CallStatus &_internalCallStatus, SensorInterface::SensorResponse &_response, const CommonAPI::CallInfo *_info) {
    if (!_sensorState.validate()) {
        _internalCallStatus = CommonAPI::CallStatus::INVALID_VALUE;
        return;
    }
    delegate_->SensorControl(_sensorId, _sensorState, _internalCallStatus, _response, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> SensorInterfaceProxy<_AttributeExtensions...>::SensorControlAsync(const int32_t &_sensorId, const SensorInterface::SensorState &_sensorState, SensorControlAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    if (!_sensorState.validate()) {
        SensorInterface::SensorResponse response = SensorInterface::SensorResponse::SENSOR_RESPONSE_SUCCESS;
        _callback(CommonAPI::CallStatus::INVALID_VALUE, response);
        std::promise<CommonAPI::CallStatus> promise;
        promise.set_value(CommonAPI::CallStatus::INVALID_VALUE);
        return promise.get_future();
    }
    return delegate_->SensorControlAsync(_sensorId, _sensorState, _callback, _info);
}

template <typename ... _AttributeExtensions>
const CommonAPI::Address &SensorInterfaceProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool SensorInterfaceProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool SensorInterfaceProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& SensorInterfaceProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& SensorInterfaceProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> SensorInterfaceProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace sensor
} // namespace qti
} // namespace qualcomm
} // namespace com
} // namespace v0



// Compatibility
namespace v0_1 = v0;

#endif // V0_COM_QUALCOMM_QTI_SENSOR_Sensor_Interface_PROXY_HPP_
