/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_COM_QUALCOMM_QTI_SENSOR_Sensor_Interface_STUB_HPP_
#define V0_COM_QUALCOMM_QTI_SENSOR_Sensor_Interface_STUB_HPP_

#include <functional>
#include <sstream>




#include <v0/com/qualcomm/qti/sensor/SensorInterface.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <cstdint>
#include <string>
#include <unordered_set>
#include <vector>


#include <CommonAPI/Stub.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace com {
namespace qualcomm {
namespace qti {
namespace sensor {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service SensorInterface. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class SensorInterfaceStubAdapter
    : public virtual CommonAPI::StubAdapter,
      public virtual SensorInterface {
 public:
    /**
    * Sends a broadcast event for SensorCapabilities. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireSensorCapabilitiesEvent(const ::v0::com::qualcomm::qti::sensor::SensorInterface::SensorCapabilitiesMask &_capsMask) = 0;
    /**
    * Sends a broadcast event for SensorConfigUpdate. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireSensorConfigUpdateEvent(const int32_t &_sensorId, const float &_samplingRate, const int32_t &_batchCount) = 0;
    /**
    * Sends a broadcast event for SensorDataRead. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireSensorDataReadEvent(const std::vector< ::v0::com::qualcomm::qti::sensor::SensorInterface::SensorEvent > &_events, const int32_t &_count) = 0;


    virtual void deactivateManagedInstances() = 0;


protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */

};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for SensorInterface.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class SensorInterfaceStubRemoteEvent
{
public:
    virtual ~SensorInterfaceStubRemoteEvent() { }

};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service SensorInterface to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class SensorInterfaceStub
    : public virtual CommonAPI::Stub<SensorInterfaceStubAdapter, SensorInterfaceStubRemoteEvent>
{
public:
    typedef std::function<void (SensorInterface::SensorResponse _response)> RegisterSensorClientReply_t;
    typedef std::function<void (SensorInterface::SensorResponse _response)> DeRegisterSensorClientReply_t;
    typedef std::function<void (std::vector< SensorInterface::SensorList > _sensor, int32_t _count)> GetSensorListReply_t;
    typedef std::function<void (SensorInterface::SensorResponse _response)> SensorConfigReply_t;
    typedef std::function<void (SensorInterface::SensorResponse _response)> SensorControlReply_t;

    virtual ~SensorInterfaceStub() {}
    void lockInterfaceVersionAttribute(bool _lockAccess) { static_cast<void>(_lockAccess); }
    bool hasElement(const uint32_t _id) const {
        return (_id < 8);
    }
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) = 0;

    /// Sends a broadcast event for SensorCapabilities.
    virtual void fireSensorCapabilitiesEvent(const ::v0::com::qualcomm::qti::sensor::SensorInterface::SensorCapabilitiesMask &_capsMask) {
        auto stubAdapter = CommonAPI::Stub<SensorInterfaceStubAdapter, SensorInterfaceStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireSensorCapabilitiesEvent(_capsMask);
    }
    /// Sends a broadcast event for SensorConfigUpdate.
    virtual void fireSensorConfigUpdateEvent(const int32_t &_sensorId, const float &_samplingRate, const int32_t &_batchCount) {
        auto stubAdapter = CommonAPI::Stub<SensorInterfaceStubAdapter, SensorInterfaceStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireSensorConfigUpdateEvent(_sensorId, _samplingRate, _batchCount);
    }
    /// Sends a broadcast event for SensorDataRead.
    virtual void fireSensorDataReadEvent(const std::vector< ::v0::com::qualcomm::qti::sensor::SensorInterface::SensorEvent > &_events, const int32_t &_count) {
        auto stubAdapter = CommonAPI::Stub<SensorInterfaceStubAdapter, SensorInterfaceStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireSensorDataReadEvent(_events, _count);
    }
    /// This is the method that will be called on remote calls on the method RegisterSensorClient.
    virtual void RegisterSensorClient(const std::shared_ptr<CommonAPI::ClientId> _client, RegisterSensorClientReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method DeRegisterSensorClient.
    virtual void DeRegisterSensorClient(const std::shared_ptr<CommonAPI::ClientId> _client, DeRegisterSensorClientReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method GetSensorList.
    virtual void GetSensorList(const std::shared_ptr<CommonAPI::ClientId> _client, GetSensorListReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method SensorConfig.
    virtual void SensorConfig(const std::shared_ptr<CommonAPI::ClientId> _client, int32_t _sensorId, float _samplingRate, int32_t _batchCount, SensorConfigReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method SensorControl.
    virtual void SensorControl(const std::shared_ptr<CommonAPI::ClientId> _client, int32_t _sensorId, SensorInterface::SensorState _sensorState, SensorControlReply_t _reply) = 0;


    using CommonAPI::Stub<SensorInterfaceStubAdapter, SensorInterfaceStubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<SensorInterfaceStubAdapter, SensorInterfaceStubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<SensorInterfaceStubAdapter, SensorInterfaceStubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef SensorInterfaceStubRemoteEvent RemoteEventType;
    typedef SensorInterface StubInterface;
};

} // namespace sensor
} // namespace qti
} // namespace qualcomm
} // namespace com
} // namespace v0


// Compatibility
namespace v0_1 = v0;

#endif // V0_COM_QUALCOMM_QTI_SENSOR_Sensor_Interface_STUB_HPP_
