/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V0_COM_QUALCOMM_QTI_SENSOR_SENSOR_INTERFACE_SOMEIP_STUB_ADAPTER_HPP_
#define V0_COM_QUALCOMM_QTI_SENSOR_SENSOR_INTERFACE_SOMEIP_STUB_ADAPTER_HPP_

#include <v0/com/qualcomm/qti/sensor/SensorInterfaceStub.hpp>
#include <v0/com/qualcomm/qti/sensor/SensorInterfaceSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace com {
namespace qualcomm {
namespace qti {
namespace sensor {

template <typename _Stub = ::v0::com::qualcomm::qti::sensor::SensorInterfaceStub, typename... _Stubs>
class SensorInterfaceSomeIPStubAdapterInternal
    : public virtual SensorInterfaceStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< SensorInterfaceSomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> SensorInterfaceSomeIPStubAdapterHelper;

    ~SensorInterfaceSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        SensorInterfaceSomeIPStubAdapterHelper::deinit();
    }

    void fireSensorCapabilitiesEvent(const ::v0::com::qualcomm::qti::sensor::SensorInterface::SensorCapabilitiesMask &_capsMask);

    void fireSensorConfigUpdateEvent(const int32_t &_sensorId, const float &_samplingRate, const int32_t &_batchCount);

    void fireSensorDataReadEvent(const std::vector< ::v0::com::qualcomm::qti::sensor::SensorInterface::SensorEvent > &_events, const int32_t &_count);

    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::com::qualcomm::qti::sensor::SensorInterfaceStub,
        CommonAPI::Version
    > getSensorInterfaceInterfaceVersionStubDispatcher;

    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::com::qualcomm::qti::sensor::SensorInterfaceStub,
        std::tuple< >,
        std::tuple< SensorInterface::SensorResponse>,
        std::tuple< >,
        std::tuple< ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorResponseDeployment_t>
    > registerSensorClientStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::com::qualcomm::qti::sensor::SensorInterfaceStub,
        std::tuple< >,
        std::tuple< SensorInterface::SensorResponse>,
        std::tuple< >,
        std::tuple< ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorResponseDeployment_t>
    > deRegisterSensorClientStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::com::qualcomm::qti::sensor::SensorInterfaceStub,
        std::tuple< >,
        std::tuple< std::vector< SensorInterface::SensorList >, int32_t>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::ArrayDeployment< ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorListDeployment_t >, CommonAPI::SomeIP::IntegerDeployment<int32_t>>
    > getSensorListStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::com::qualcomm::qti::sensor::SensorInterfaceStub,
        std::tuple< int32_t, float, int32_t>,
        std::tuple< SensorInterface::SensorResponse>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<int32_t>, CommonAPI::EmptyDeployment, CommonAPI::SomeIP::IntegerDeployment<int32_t>>,
        std::tuple< ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorResponseDeployment_t>
    > sensorConfigStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::com::qualcomm::qti::sensor::SensorInterfaceStub,
        std::tuple< int32_t, SensorInterface::SensorState>,
        std::tuple< SensorInterface::SensorResponse>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<int32_t>, ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorStateDeployment_t>,
        std::tuple< ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorResponseDeployment_t>
    > sensorControlStubDispatcher;
    
    SensorInterfaceSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        SensorInterfaceSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< SensorInterfaceStub>(_stub)),
        getSensorInterfaceInterfaceVersionStubDispatcher(&SensorInterfaceStub::lockInterfaceVersionAttribute, &SensorInterfaceStub::getInterfaceVersion, false, true),
        registerSensorClientStubDispatcher(
            &SensorInterfaceStub::RegisterSensorClient,
            false,
            _stub->hasElement(3),
            std::make_tuple(),
            std::make_tuple(&::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorResponseDeployment))
        
        ,
        deRegisterSensorClientStubDispatcher(
            &SensorInterfaceStub::DeRegisterSensorClient,
            false,
            _stub->hasElement(4),
            std::make_tuple(),
            std::make_tuple(&::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorResponseDeployment))
        
        ,
        getSensorListStubDispatcher(
            &SensorInterfaceStub::GetSensorList,
            false,
            _stub->hasElement(5),
            std::make_tuple(),
            std::make_tuple(static_cast< CommonAPI::SomeIP::ArrayDeployment< ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorListDeployment_t >* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr)))
        
        ,
        sensorConfigStubDispatcher(
            &SensorInterfaceStub::SensorConfig,
            false,
            _stub->hasElement(6),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr), static_cast< CommonAPI::EmptyDeployment* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr)),
            std::make_tuple(&::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorResponseDeployment))
        
        ,
        sensorControlStubDispatcher(
            &SensorInterfaceStub::SensorControl,
            false,
            _stub->hasElement(7),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr), &::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorStateDeployment),
            std::make_tuple(&::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorResponseDeployment))
        
    {
        SensorInterfaceSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x7531) }, &registerSensorClientStubDispatcher );
        SensorInterfaceSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x7532) }, &deRegisterSensorClientStubDispatcher );
        SensorInterfaceSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x7533) }, &getSensorListStubDispatcher );
        SensorInterfaceSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x7534) }, &sensorConfigStubDispatcher );
        SensorInterfaceSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x7535) }, &sensorControlStubDispatcher );
        // Provided events/fields
        {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0x9472));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x9475), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_EVENT, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
        }
        {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0x9472));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x9476), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_EVENT, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
        }
        {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0x9472));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x9477), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_EVENT, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
        }
    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};

template <typename _Stub, typename... _Stubs>
void SensorInterfaceSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireSensorCapabilitiesEvent(const ::v0::com::qualcomm::qti::sensor::SensorInterface::SensorCapabilitiesMask &_capsMask) {
    CommonAPI::Deployable< SensorInterface::SensorCapabilitiesMask, ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorCapabilitiesMaskDeployment_t> deployed_capsMask(_capsMask, &::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorCapabilitiesMaskDeployment);
    CommonAPI::SomeIP::StubEventHelper<CommonAPI::SomeIP::SerializableArguments<  CommonAPI::Deployable< ::v0::com::qualcomm::qti::sensor::SensorInterface::SensorCapabilitiesMask, ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorCapabilitiesMaskDeployment_t > 
    >>
        ::sendEvent(
            *this,
            CommonAPI::SomeIP::event_id_t(0x9475),
            false,
             deployed_capsMask 
    );
}

template <typename _Stub, typename... _Stubs>
void SensorInterfaceSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireSensorConfigUpdateEvent(const int32_t &_sensorId, const float &_samplingRate, const int32_t &_batchCount) {
    CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t>> deployed_sensorId(_sensorId, static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr));
    CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t>> deployed_batchCount(_batchCount, static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<CommonAPI::SomeIP::SerializableArguments<  CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t> > 
    ,  float
    ,  CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t> > 
    >>
        ::sendEvent(
            *this,
            CommonAPI::SomeIP::event_id_t(0x9476),
            false,
             deployed_sensorId 
            , _samplingRate
            ,  deployed_batchCount 
    );
}

template <typename _Stub, typename... _Stubs>
void SensorInterfaceSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireSensorDataReadEvent(const std::vector< ::v0::com::qualcomm::qti::sensor::SensorInterface::SensorEvent > &_events, const int32_t &_count) {
    CommonAPI::Deployable< std::vector< SensorInterface::SensorEvent >, CommonAPI::SomeIP::ArrayDeployment< ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorEventDeployment_t >> deployed_events(_events, static_cast< CommonAPI::SomeIP::ArrayDeployment< ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorEventDeployment_t >* >(nullptr));
    CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t>> deployed_count(_count, static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<CommonAPI::SomeIP::SerializableArguments<  CommonAPI::Deployable< std::vector< ::v0::com::qualcomm::qti::sensor::SensorInterface::SensorEvent >, CommonAPI::SomeIP::ArrayDeployment< ::v0::com::qualcomm::qti::sensor::SensorInterface_::SensorEventDeployment_t > > 
    ,  CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t> > 
    >>
        ::sendEvent(
            *this,
            CommonAPI::SomeIP::event_id_t(0x9477),
            false,
             deployed_events 
            ,  deployed_count 
    );
}


template <typename _Stub, typename... _Stubs>
void SensorInterfaceSomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {
}

template <typename _Stub, typename... _Stubs>
void SensorInterfaceSomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {
}

template <typename _Stub = ::v0::com::qualcomm::qti::sensor::SensorInterfaceStub, typename... _Stubs>
class SensorInterfaceSomeIPStubAdapter
    : public SensorInterfaceSomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    SensorInterfaceSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          SensorInterfaceSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace sensor
} // namespace qti
} // namespace qualcomm
} // namespace com
} // namespace v0

#endif // V0_COM_QUALCOMM_QTI_SENSOR_Sensor_Interface_SOMEIP_STUB_ADAPTER_HPP_
