/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COM_QUALCOMM_QTI_SENSOR_Sensor_Interface_PROXY_BASE_HPP_
#define V1_COM_QUALCOMM_QTI_SENSOR_Sensor_Interface_PROXY_BASE_HPP_

#include <v1/com/qualcomm/qti/sensor/SensorInterface.hpp>


#include <v1/com/qualcomm/qti/sensor/SensorInterfaceTypes.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <cstdint>
#include <string>
#include <vector>

#include <CommonAPI/Event.hpp>
#include <CommonAPI/Proxy.hpp>
#include <functional>
#include <future>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace com {
namespace qualcomm {
namespace qti {
namespace sensor {

class SensorInterfaceProxyBase
    : virtual public CommonAPI::Proxy {
public:
    typedef CommonAPI::Event<
        ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorServiceStateMaskT
    > SensorCapabilitiesEvent;
    typedef CommonAPI::Event<
        int32_t, float, int32_t
    > SensorConfigUpdateEvent;
    typedef CommonAPI::Event<
        std::vector< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorImuEventT >, int32_t
    > SensorImuDataReadEvent;
    typedef CommonAPI::Event<
        std::vector< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorHeadEventT >, int32_t
    > SensorHeadingDataReadEvent;

    typedef std::function<void(const CommonAPI::CallStatus&, const ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT&)> RegisterSensorClientReqAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT&)> DeRegisterSensorClientReqAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const std::vector< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorInfoT >&, const int32_t&)> GetSensorListReqAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT&)> SensorConfigReqAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT&)> SensorControlReqAsyncCallback;

    virtual SensorCapabilitiesEvent& getSensorCapabilitiesEvent() = 0;
    virtual SensorConfigUpdateEvent& getSensorConfigUpdateEvent() = 0;
    virtual SensorImuDataReadEvent& getSensorImuDataReadEvent() = 0;
    virtual SensorHeadingDataReadEvent& getSensorHeadingDataReadEvent() = 0;
    virtual void RegisterSensorClientReq(CommonAPI::CallStatus &_internalCallStatus, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT &_SensorResponse, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> RegisterSensorClientReqAsync(RegisterSensorClientReqAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual void DeRegisterSensorClientReq(CommonAPI::CallStatus &_internalCallStatus, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT &_SensorResponse, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> DeRegisterSensorClientReqAsync(DeRegisterSensorClientReqAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual void GetSensorListReq(CommonAPI::CallStatus &_internalCallStatus, std::vector< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorInfoT > &_SensorList, int32_t &_count, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> GetSensorListReqAsync(GetSensorListReqAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual void SensorConfigReq(int32_t _sensorId, float _samplingRate, int32_t _batchCount, CommonAPI::CallStatus &_internalCallStatus, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT &_SensorResponse, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> SensorConfigReqAsync(const int32_t &_sensorId, const float &_samplingRate, const int32_t &_batchCount, SensorConfigReqAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual void SensorControlReq(int32_t _sensorId, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorStateT _sensorState, CommonAPI::CallStatus &_internalCallStatus, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT &_SensorResponse, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> SensorControlReqAsync(const int32_t &_sensorId, const ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorStateT &_sensorState, SensorControlReqAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;

    virtual std::future<void> getCompletionFuture() = 0;
};

} // namespace sensor
} // namespace qti
} // namespace qualcomm
} // namespace com
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_COM_QUALCOMM_QTI_SENSOR_Sensor_Interface_PROXY_BASE_HPP_
