/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COM_QUALCOMM_QTI_SENSOR_Sensor_Interface_Types_HPP_
#define V1_COM_QUALCOMM_QTI_SENSOR_Sensor_Interface_Types_HPP_



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <CommonAPI/Types.hpp>
#include <cstdint>
#include <string>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace com {
namespace qualcomm {
namespace qti {
namespace sensor {

struct SensorInterfaceTypes {
    
    struct SensorReturnT : CommonAPI::Enumeration< uint8_t> {
        enum Literal : uint8_t {
            SENSOR_RETURN_UNKNOWN = 0,
            SENSOR_RETURN_SUCCESS = 1,
            SENSOR_RETURN_ERROR_CLIENT_REGISTER_FAILED = 2,
            SENSOR_RETURN_ERROR_INVALID_CLIENT = 3,
            SENSOR_RETURN_ERROR_INVALID_INPUT_PARAMETER = 4,
            SENSOR_RETURN_ERROR_CONTROL_FAILED = 5,
            SENSOR_RETURN_ERROR_CONFIG_FAILED = 6,
            SENSOR_RETURN_ERROR_NO_SENSORS_FOUND = 7,
            SENSOR_RETURN_ERROR_TRACKING_FAILED = 8,
            SENSOR_RETURN_ERROR_UNKNOWN = 9
        };
    
        SensorReturnT()
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(Literal::SENSOR_RETURN_UNKNOWN)) {}
        SensorReturnT(Literal _literal)
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< uint8_t>(Literal::SENSOR_RETURN_UNKNOWN):
                case static_cast< uint8_t>(Literal::SENSOR_RETURN_SUCCESS):
                case static_cast< uint8_t>(Literal::SENSOR_RETURN_ERROR_CLIENT_REGISTER_FAILED):
                case static_cast< uint8_t>(Literal::SENSOR_RETURN_ERROR_INVALID_CLIENT):
                case static_cast< uint8_t>(Literal::SENSOR_RETURN_ERROR_INVALID_INPUT_PARAMETER):
                case static_cast< uint8_t>(Literal::SENSOR_RETURN_ERROR_CONTROL_FAILED):
                case static_cast< uint8_t>(Literal::SENSOR_RETURN_ERROR_CONFIG_FAILED):
                case static_cast< uint8_t>(Literal::SENSOR_RETURN_ERROR_NO_SENSORS_FOUND):
                case static_cast< uint8_t>(Literal::SENSOR_RETURN_ERROR_TRACKING_FAILED):
                case static_cast< uint8_t>(Literal::SENSOR_RETURN_ERROR_UNKNOWN):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const SensorReturnT &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const SensorReturnT &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const SensorReturnT &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const SensorReturnT &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const SensorReturnT &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const SensorReturnT &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< uint8_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< uint8_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< uint8_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< uint8_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< uint8_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< uint8_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< uint8_t>(Literal::SENSOR_RETURN_UNKNOWN): return "SENSOR_RETURN_UNKNOWN";
            case static_cast< uint8_t>(Literal::SENSOR_RETURN_SUCCESS): return "SENSOR_RETURN_SUCCESS";
            case static_cast< uint8_t>(Literal::SENSOR_RETURN_ERROR_CLIENT_REGISTER_FAILED): return "SENSOR_RETURN_ERROR_CLIENT_REGISTER_FAILED";
            case static_cast< uint8_t>(Literal::SENSOR_RETURN_ERROR_INVALID_CLIENT): return "SENSOR_RETURN_ERROR_INVALID_CLIENT";
            case static_cast< uint8_t>(Literal::SENSOR_RETURN_ERROR_INVALID_INPUT_PARAMETER): return "SENSOR_RETURN_ERROR_INVALID_INPUT_PARAMETER";
            case static_cast< uint8_t>(Literal::SENSOR_RETURN_ERROR_CONTROL_FAILED): return "SENSOR_RETURN_ERROR_CONTROL_FAILED";
            case static_cast< uint8_t>(Literal::SENSOR_RETURN_ERROR_CONFIG_FAILED): return "SENSOR_RETURN_ERROR_CONFIG_FAILED";
            case static_cast< uint8_t>(Literal::SENSOR_RETURN_ERROR_NO_SENSORS_FOUND): return "SENSOR_RETURN_ERROR_NO_SENSORS_FOUND";
            case static_cast< uint8_t>(Literal::SENSOR_RETURN_ERROR_TRACKING_FAILED): return "SENSOR_RETURN_ERROR_TRACKING_FAILED";
            case static_cast< uint8_t>(Literal::SENSOR_RETURN_ERROR_UNKNOWN): return "SENSOR_RETURN_ERROR_UNKNOWN";
            default: return "UNDEFINED";
            }
        }
    };
    
    struct SensorTypeT : CommonAPI::Enumeration< uint8_t> {
        enum Literal : uint8_t {
            SENSOR_TYPE_META_UNKNOWN = 0,
            SENSOR_TYPE_META_DATA = 1,
            SENSOR_TYPE_ACCELEROMETER = 2,
            SENSOR_TYPE_GYROSCOPE = 4,
            SENSOR_TYPE_GYROSCOPE_UNCALIBRATED = 16,
            SENSOR_TYPE_ACCELEROMETER_UNCALIBRATED = 35,
            SENSOR_TYPE_HEADING = 42
        };
    
        SensorTypeT()
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(Literal::SENSOR_TYPE_META_UNKNOWN)) {}
        SensorTypeT(Literal _literal)
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< uint8_t>(Literal::SENSOR_TYPE_META_UNKNOWN):
                case static_cast< uint8_t>(Literal::SENSOR_TYPE_META_DATA):
                case static_cast< uint8_t>(Literal::SENSOR_TYPE_ACCELEROMETER):
                case static_cast< uint8_t>(Literal::SENSOR_TYPE_GYROSCOPE):
                case static_cast< uint8_t>(Literal::SENSOR_TYPE_GYROSCOPE_UNCALIBRATED):
                case static_cast< uint8_t>(Literal::SENSOR_TYPE_ACCELEROMETER_UNCALIBRATED):
                case static_cast< uint8_t>(Literal::SENSOR_TYPE_HEADING):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const SensorTypeT &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const SensorTypeT &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const SensorTypeT &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const SensorTypeT &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const SensorTypeT &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const SensorTypeT &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< uint8_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< uint8_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< uint8_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< uint8_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< uint8_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< uint8_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< uint8_t>(Literal::SENSOR_TYPE_META_UNKNOWN): return "SENSOR_TYPE_META_UNKNOWN";
            case static_cast< uint8_t>(Literal::SENSOR_TYPE_META_DATA): return "SENSOR_TYPE_META_DATA";
            case static_cast< uint8_t>(Literal::SENSOR_TYPE_ACCELEROMETER): return "SENSOR_TYPE_ACCELEROMETER";
            case static_cast< uint8_t>(Literal::SENSOR_TYPE_GYROSCOPE): return "SENSOR_TYPE_GYROSCOPE";
            case static_cast< uint8_t>(Literal::SENSOR_TYPE_GYROSCOPE_UNCALIBRATED): return "SENSOR_TYPE_GYROSCOPE_UNCALIBRATED";
            case static_cast< uint8_t>(Literal::SENSOR_TYPE_ACCELEROMETER_UNCALIBRATED): return "SENSOR_TYPE_ACCELEROMETER_UNCALIBRATED";
            case static_cast< uint8_t>(Literal::SENSOR_TYPE_HEADING): return "SENSOR_TYPE_HEADING";
            default: return "UNDEFINED";
            }
        }
    };
    
    struct SensorStateT : CommonAPI::Enumeration< uint8_t> {
        enum Literal : uint8_t {
            SENSOR_STATE_UNKNOWN = 0,
            SENSOR_STATE_DISABLE = 1,
            SENSOR_STATE_ENABLE = 2
        };
    
        SensorStateT()
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(Literal::SENSOR_STATE_UNKNOWN)) {}
        SensorStateT(Literal _literal)
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< uint8_t>(Literal::SENSOR_STATE_UNKNOWN):
                case static_cast< uint8_t>(Literal::SENSOR_STATE_DISABLE):
                case static_cast< uint8_t>(Literal::SENSOR_STATE_ENABLE):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const SensorStateT &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const SensorStateT &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const SensorStateT &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const SensorStateT &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const SensorStateT &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const SensorStateT &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< uint8_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< uint8_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< uint8_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< uint8_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< uint8_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< uint8_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< uint8_t>(Literal::SENSOR_STATE_UNKNOWN): return "SENSOR_STATE_UNKNOWN";
            case static_cast< uint8_t>(Literal::SENSOR_STATE_DISABLE): return "SENSOR_STATE_DISABLE";
            case static_cast< uint8_t>(Literal::SENSOR_STATE_ENABLE): return "SENSOR_STATE_ENABLE";
            default: return "UNDEFINED";
            }
        }
    };
    
    struct SensorServiceStateMaskT : CommonAPI::Enumeration< uint8_t> {
        enum Literal : uint8_t {
            SENSOR_SERVICE_STATE_MASK_UNKNOWN = 0,
            SENSOR_SERVICE_STATE_MASK_READY = 1
        };
    
        SensorServiceStateMaskT()
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(Literal::SENSOR_SERVICE_STATE_MASK_UNKNOWN)) {}
        SensorServiceStateMaskT(Literal _literal)
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< uint8_t>(Literal::SENSOR_SERVICE_STATE_MASK_UNKNOWN):
                case static_cast< uint8_t>(Literal::SENSOR_SERVICE_STATE_MASK_READY):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const SensorServiceStateMaskT &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const SensorServiceStateMaskT &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const SensorServiceStateMaskT &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const SensorServiceStateMaskT &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const SensorServiceStateMaskT &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const SensorServiceStateMaskT &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< uint8_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< uint8_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< uint8_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< uint8_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< uint8_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< uint8_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< uint8_t>(Literal::SENSOR_SERVICE_STATE_MASK_UNKNOWN): return "SENSOR_SERVICE_STATE_MASK_UNKNOWN";
            case static_cast< uint8_t>(Literal::SENSOR_SERVICE_STATE_MASK_READY): return "SENSOR_SERVICE_STATE_MASK_READY";
            default: return "UNDEFINED";
            }
        }
    };
    struct SensorResponseT : CommonAPI::Struct< SensorReturnT> {
    
        SensorResponseT()
        {
            std::get< 0>(values_) = SensorReturnT();
        }
        SensorResponseT(const SensorReturnT &_SensorResponse)
        {
            std::get< 0>(values_) = _SensorResponse;
        }
        inline const SensorReturnT &getSensorResponse() const { return std::get< 0>(values_); }
        inline void setSensorResponse(const SensorReturnT &_value) { std::get< 0>(values_) = _value; }
        inline bool operator==(const SensorResponseT& _other) const {
        return (getSensorResponse() == _other.getSensorResponse());
        }
        inline bool operator!=(const SensorResponseT &_other) const {
            return !((*this) == _other);
        }
    
    };
    struct SensorInfoT : CommonAPI::Struct< int32_t, std::string, std::string, int32_t, int32_t, float, int32_t, int32_t, std::vector< float >, float, float> {
    
        SensorInfoT()
        {
            std::get< 0>(values_) = 0;
            std::get< 1>(values_) = "";
            std::get< 2>(values_) = "";
            std::get< 3>(values_) = 0;
            std::get< 4>(values_) = 0;
            std::get< 5>(values_) = 0.0f;
            std::get< 6>(values_) = 0;
            std::get< 7>(values_) = 0;
            std::get< 8>(values_) = std::vector< float >();
            std::get< 9>(values_) = 0.0f;
            std::get< 10>(values_) = 0.0f;
        }
        SensorInfoT(const int32_t &_sensorVersion, const std::string &_name, const std::string &_vendor, const int32_t &_sensorId, const int32_t &_type, const float &_maxSamplingRate, const int32_t &_minBatchCount, const int32_t &_maxBatchCount, const std::vector< float > &_odr, const float &_resolution, const float &_maxRange)
        {
            std::get< 0>(values_) = _sensorVersion;
            std::get< 1>(values_) = _name;
            std::get< 2>(values_) = _vendor;
            std::get< 3>(values_) = _sensorId;
            std::get< 4>(values_) = _type;
            std::get< 5>(values_) = _maxSamplingRate;
            std::get< 6>(values_) = _minBatchCount;
            std::get< 7>(values_) = _maxBatchCount;
            std::get< 8>(values_) = _odr;
            std::get< 9>(values_) = _resolution;
            std::get< 10>(values_) = _maxRange;
        }
        inline const int32_t &getSensorVersion() const { return std::get< 0>(values_); }
        inline void setSensorVersion(const int32_t &_value) { std::get< 0>(values_) = _value; }
        inline const std::string &getName() const { return std::get< 1>(values_); }
        inline void setName(const std::string &_value) { std::get< 1>(values_) = _value; }
        inline const std::string &getVendor() const { return std::get< 2>(values_); }
        inline void setVendor(const std::string &_value) { std::get< 2>(values_) = _value; }
        inline const int32_t &getSensorId() const { return std::get< 3>(values_); }
        inline void setSensorId(const int32_t &_value) { std::get< 3>(values_) = _value; }
        inline const int32_t &getType() const { return std::get< 4>(values_); }
        inline void setType(const int32_t &_value) { std::get< 4>(values_) = _value; }
        inline const float &getMaxSamplingRate() const { return std::get< 5>(values_); }
        inline void setMaxSamplingRate(const float &_value) { std::get< 5>(values_) = _value; }
        inline const int32_t &getMinBatchCount() const { return std::get< 6>(values_); }
        inline void setMinBatchCount(const int32_t &_value) { std::get< 6>(values_) = _value; }
        inline const int32_t &getMaxBatchCount() const { return std::get< 7>(values_); }
        inline void setMaxBatchCount(const int32_t &_value) { std::get< 7>(values_) = _value; }
        inline const std::vector< float > &getOdr() const { return std::get< 8>(values_); }
        inline void setOdr(const std::vector< float > &_value) { std::get< 8>(values_) = _value; }
        inline const float &getResolution() const { return std::get< 9>(values_); }
        inline void setResolution(const float &_value) { std::get< 9>(values_) = _value; }
        inline const float &getMaxRange() const { return std::get< 10>(values_); }
        inline void setMaxRange(const float &_value) { std::get< 10>(values_) = _value; }
        inline bool operator==(const SensorInfoT& _other) const {
        return (getSensorVersion() == _other.getSensorVersion() && getName() == _other.getName() && getVendor() == _other.getVendor() && getSensorId() == _other.getSensorId() && getType() == _other.getType() && getMaxSamplingRate() == _other.getMaxSamplingRate() && getMinBatchCount() == _other.getMinBatchCount() && getMaxBatchCount() == _other.getMaxBatchCount() && getOdr() == _other.getOdr() && getResolution() == _other.getResolution() && getMaxRange() == _other.getMaxRange());
        }
        inline bool operator!=(const SensorInfoT &_other) const {
            return !((*this) == _other);
        }
    
    };
    struct GetSensorListResponseT : CommonAPI::Struct< std::vector< SensorInfoT >, int32_t> {
    
        GetSensorListResponseT()
        {
            std::get< 0>(values_) = std::vector< SensorInfoT >();
            std::get< 1>(values_) = 0;
        }
        GetSensorListResponseT(const std::vector< SensorInfoT > &_SensorList, const int32_t &_count)
        {
            std::get< 0>(values_) = _SensorList;
            std::get< 1>(values_) = _count;
        }
        inline const std::vector< SensorInfoT > &getSensorList() const { return std::get< 0>(values_); }
        inline void setSensorList(const std::vector< SensorInfoT > &_value) { std::get< 0>(values_) = _value; }
        inline const int32_t &getCount() const { return std::get< 1>(values_); }
        inline void setCount(const int32_t &_value) { std::get< 1>(values_) = _value; }
        inline bool operator==(const GetSensorListResponseT& _other) const {
        return (getSensorList() == _other.getSensorList() && getCount() == _other.getCount());
        }
        inline bool operator!=(const GetSensorListResponseT &_other) const {
            return !((*this) == _other);
        }
    
    };
    struct SensorConfigRequestT : CommonAPI::Struct< int32_t, float, int32_t> {
    
        SensorConfigRequestT()
        {
            std::get< 0>(values_) = 0;
            std::get< 1>(values_) = 0.0f;
            std::get< 2>(values_) = 0;
        }
        SensorConfigRequestT(const int32_t &_sensorId, const float &_samplingRate, const int32_t &_batchCount)
        {
            std::get< 0>(values_) = _sensorId;
            std::get< 1>(values_) = _samplingRate;
            std::get< 2>(values_) = _batchCount;
        }
        inline const int32_t &getSensorId() const { return std::get< 0>(values_); }
        inline void setSensorId(const int32_t &_value) { std::get< 0>(values_) = _value; }
        inline const float &getSamplingRate() const { return std::get< 1>(values_); }
        inline void setSamplingRate(const float &_value) { std::get< 1>(values_) = _value; }
        inline const int32_t &getBatchCount() const { return std::get< 2>(values_); }
        inline void setBatchCount(const int32_t &_value) { std::get< 2>(values_) = _value; }
        inline bool operator==(const SensorConfigRequestT& _other) const {
        return (getSensorId() == _other.getSensorId() && getSamplingRate() == _other.getSamplingRate() && getBatchCount() == _other.getBatchCount());
        }
        inline bool operator!=(const SensorConfigRequestT &_other) const {
            return !((*this) == _other);
        }
    
    };
    struct SensorControlRequestT : CommonAPI::Struct< int32_t, SensorStateT> {
    
        SensorControlRequestT()
        {
            std::get< 0>(values_) = 0;
            std::get< 1>(values_) = SensorStateT();
        }
        SensorControlRequestT(const int32_t &_sensorId, const SensorStateT &_sensorState)
        {
            std::get< 0>(values_) = _sensorId;
            std::get< 1>(values_) = _sensorState;
        }
        inline const int32_t &getSensorId() const { return std::get< 0>(values_); }
        inline void setSensorId(const int32_t &_value) { std::get< 0>(values_) = _value; }
        inline const SensorStateT &getSensorState() const { return std::get< 1>(values_); }
        inline void setSensorState(const SensorStateT &_value) { std::get< 1>(values_) = _value; }
        inline bool operator==(const SensorControlRequestT& _other) const {
        return (getSensorId() == _other.getSensorId() && getSensorState() == _other.getSensorState());
        }
        inline bool operator!=(const SensorControlRequestT &_other) const {
            return !((*this) == _other);
        }
    
    };
    struct SensorUncalibratedEventT : CommonAPI::Struct< float, float, float, float, float, float> {
    
        SensorUncalibratedEventT()
        {
            std::get< 0>(values_) = 0.0f;
            std::get< 1>(values_) = 0.0f;
            std::get< 2>(values_) = 0.0f;
            std::get< 3>(values_) = 0.0f;
            std::get< 4>(values_) = 0.0f;
            std::get< 5>(values_) = 0.0f;
        }
        SensorUncalibratedEventT(const float &_xUncalib, const float &_yUncalib, const float &_zUncalib, const float &_xBias, const float &_yBias, const float &_zBias)
        {
            std::get< 0>(values_) = _xUncalib;
            std::get< 1>(values_) = _yUncalib;
            std::get< 2>(values_) = _zUncalib;
            std::get< 3>(values_) = _xBias;
            std::get< 4>(values_) = _yBias;
            std::get< 5>(values_) = _zBias;
        }
        inline const float &getXUncalib() const { return std::get< 0>(values_); }
        inline void setXUncalib(const float &_value) { std::get< 0>(values_) = _value; }
        inline const float &getYUncalib() const { return std::get< 1>(values_); }
        inline void setYUncalib(const float &_value) { std::get< 1>(values_) = _value; }
        inline const float &getZUncalib() const { return std::get< 2>(values_); }
        inline void setZUncalib(const float &_value) { std::get< 2>(values_) = _value; }
        inline const float &getXBias() const { return std::get< 3>(values_); }
        inline void setXBias(const float &_value) { std::get< 3>(values_) = _value; }
        inline const float &getYBias() const { return std::get< 4>(values_); }
        inline void setYBias(const float &_value) { std::get< 4>(values_) = _value; }
        inline const float &getZBias() const { return std::get< 5>(values_); }
        inline void setZBias(const float &_value) { std::get< 5>(values_) = _value; }
        inline bool operator==(const SensorUncalibratedEventT& _other) const {
        return (getXUncalib() == _other.getXUncalib() && getYUncalib() == _other.getYUncalib() && getZUncalib() == _other.getZUncalib() && getXBias() == _other.getXBias() && getYBias() == _other.getYBias() && getZBias() == _other.getZBias());
        }
        inline bool operator!=(const SensorUncalibratedEventT &_other) const {
            return !((*this) == _other);
        }
    
    };
    struct SensorImuEventT : CommonAPI::Struct< int32_t, int32_t, uint64_t, uint64_t, SensorUncalibratedEventT> {
    
        SensorImuEventT()
        {
            std::get< 0>(values_) = 0;
            std::get< 1>(values_) = 0;
            std::get< 2>(values_) = 0ull;
            std::get< 3>(values_) = 0ull;
            std::get< 4>(values_) = SensorUncalibratedEventT();
        }
        SensorImuEventT(const int32_t &_sensorId, const int32_t &_type, const uint64_t &_timestamp, const uint64_t &_gptpTimestamp, const SensorUncalibratedEventT &_data)
        {
            std::get< 0>(values_) = _sensorId;
            std::get< 1>(values_) = _type;
            std::get< 2>(values_) = _timestamp;
            std::get< 3>(values_) = _gptpTimestamp;
            std::get< 4>(values_) = _data;
        }
        inline const int32_t &getSensorId() const { return std::get< 0>(values_); }
        inline void setSensorId(const int32_t &_value) { std::get< 0>(values_) = _value; }
        inline const int32_t &getType() const { return std::get< 1>(values_); }
        inline void setType(const int32_t &_value) { std::get< 1>(values_) = _value; }
        inline const uint64_t &getTimestamp() const { return std::get< 2>(values_); }
        inline void setTimestamp(const uint64_t &_value) { std::get< 2>(values_) = _value; }
        inline const uint64_t &getGptpTimestamp() const { return std::get< 3>(values_); }
        inline void setGptpTimestamp(const uint64_t &_value) { std::get< 3>(values_) = _value; }
        inline const SensorUncalibratedEventT &getData() const { return std::get< 4>(values_); }
        inline void setData(const SensorUncalibratedEventT &_value) { std::get< 4>(values_) = _value; }
        inline bool operator==(const SensorImuEventT& _other) const {
        return (getSensorId() == _other.getSensorId() && getType() == _other.getType() && getTimestamp() == _other.getTimestamp() && getGptpTimestamp() == _other.getGptpTimestamp() && getData() == _other.getData());
        }
        inline bool operator!=(const SensorImuEventT &_other) const {
            return !((*this) == _other);
        }
    
    };
    struct SensorHeadingEventT : CommonAPI::Struct< float, float> {
    
        SensorHeadingEventT()
        {
            std::get< 0>(values_) = 0.0f;
            std::get< 1>(values_) = 0.0f;
        }
        SensorHeadingEventT(const float &_heading, const float &_accuracy)
        {
            std::get< 0>(values_) = _heading;
            std::get< 1>(values_) = _accuracy;
        }
        inline const float &getHeading() const { return std::get< 0>(values_); }
        inline void setHeading(const float &_value) { std::get< 0>(values_) = _value; }
        inline const float &getAccuracy() const { return std::get< 1>(values_); }
        inline void setAccuracy(const float &_value) { std::get< 1>(values_) = _value; }
        inline bool operator==(const SensorHeadingEventT& _other) const {
        return (getHeading() == _other.getHeading() && getAccuracy() == _other.getAccuracy());
        }
        inline bool operator!=(const SensorHeadingEventT &_other) const {
            return !((*this) == _other);
        }
    
    };
    struct SensorHeadEventT : CommonAPI::Struct< int32_t, int32_t, uint64_t, uint64_t, SensorHeadingEventT> {
    
        SensorHeadEventT()
        {
            std::get< 0>(values_) = 0;
            std::get< 1>(values_) = 0;
            std::get< 2>(values_) = 0ull;
            std::get< 3>(values_) = 0ull;
            std::get< 4>(values_) = SensorHeadingEventT();
        }
        SensorHeadEventT(const int32_t &_sensorId, const int32_t &_type, const uint64_t &_timestamp, const uint64_t &_gptpTimestamp, const SensorHeadingEventT &_data)
        {
            std::get< 0>(values_) = _sensorId;
            std::get< 1>(values_) = _type;
            std::get< 2>(values_) = _timestamp;
            std::get< 3>(values_) = _gptpTimestamp;
            std::get< 4>(values_) = _data;
        }
        inline const int32_t &getSensorId() const { return std::get< 0>(values_); }
        inline void setSensorId(const int32_t &_value) { std::get< 0>(values_) = _value; }
        inline const int32_t &getType() const { return std::get< 1>(values_); }
        inline void setType(const int32_t &_value) { std::get< 1>(values_) = _value; }
        inline const uint64_t &getTimestamp() const { return std::get< 2>(values_); }
        inline void setTimestamp(const uint64_t &_value) { std::get< 2>(values_) = _value; }
        inline const uint64_t &getGptpTimestamp() const { return std::get< 3>(values_); }
        inline void setGptpTimestamp(const uint64_t &_value) { std::get< 3>(values_) = _value; }
        inline const SensorHeadingEventT &getData() const { return std::get< 4>(values_); }
        inline void setData(const SensorHeadingEventT &_value) { std::get< 4>(values_) = _value; }
        inline bool operator==(const SensorHeadEventT& _other) const {
        return (getSensorId() == _other.getSensorId() && getType() == _other.getType() && getTimestamp() == _other.getTimestamp() && getGptpTimestamp() == _other.getGptpTimestamp() && getData() == _other.getData());
        }
        inline bool operator!=(const SensorHeadEventT &_other) const {
            return !((*this) == _other);
        }
    
    };


static inline const char* getTypeCollectionName() {
    static const char* typeCollectionName = "com.qualcomm.qti.sensor.SensorInterfaceTypes";
    return typeCollectionName;
}

inline CommonAPI::Version getTypeCollectionVersion() {
    return CommonAPI::Version(1, 0);
}

}; // struct SensorInterfaceTypes

} // namespace sensor
} // namespace qti
} // namespace qualcomm
} // namespace com
} // namespace v1

namespace CommonAPI {
}


namespace std {
    //Hash for SensorReturnT
    template<>
    struct hash< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT> {
        inline size_t operator()(const ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT& sensorReturnT) const {
            return static_cast< uint8_t>(sensorReturnT);
        }
    };
    //Hash for SensorTypeT
    template<>
    struct hash< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorTypeT> {
        inline size_t operator()(const ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorTypeT& sensorTypeT) const {
            return static_cast< uint8_t>(sensorTypeT);
        }
    };
    //Hash for SensorStateT
    template<>
    struct hash< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorStateT> {
        inline size_t operator()(const ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorStateT& sensorStateT) const {
            return static_cast< uint8_t>(sensorStateT);
        }
    };
    //Hash for SensorServiceStateMaskT
    template<>
    struct hash< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorServiceStateMaskT> {
        inline size_t operator()(const ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorServiceStateMaskT& sensorServiceStateMaskT) const {
            return static_cast< uint8_t>(sensorServiceStateMaskT);
        }
    };
}


// Compatibility
namespace v1_0 = v1;

#endif // V1_COM_QUALCOMM_QTI_SENSOR_Sensor_Interface_Types_HPP_
