/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V1_COM_QUALCOMM_QTI_SENSOR_SENSOR_INTERFACE_SOMEIP_STUB_ADAPTER_HPP_
#define V1_COM_QUALCOMM_QTI_SENSOR_SENSOR_INTERFACE_SOMEIP_STUB_ADAPTER_HPP_

#include <v1/com/qualcomm/qti/sensor/SensorInterfaceStub.hpp>
#include <v1/com/qualcomm/qti/sensor/SensorInterfaceSomeIPDeployment.hpp>
#include <v1/com/qualcomm/qti/sensor/SensorInterfaceTypesSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace com {
namespace qualcomm {
namespace qti {
namespace sensor {

template <typename _Stub = ::v1::com::qualcomm::qti::sensor::SensorInterfaceStub, typename... _Stubs>
class SensorInterfaceSomeIPStubAdapterInternal
    : public virtual SensorInterfaceStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< SensorInterfaceSomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> SensorInterfaceSomeIPStubAdapterHelper;

    ~SensorInterfaceSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        SensorInterfaceSomeIPStubAdapterHelper::deinit();
    }

    void fireSensorCapabilitiesEvent(const ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorServiceStateMaskT &_SensorCapabilitiesMask);

    void fireSensorConfigUpdateEvent(const int32_t &_sensorId, const float &_samplingRate, const int32_t &_batchCount);

    void fireSensorImuDataReadEvent(const std::vector< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorImuEventT > &_SensorImuEvent, const int32_t &_count);

    void fireSensorHeadingDataReadEvent(const std::vector< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorHeadEventT > &_sensorHeadEvent, const int32_t &_count);

    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::com::qualcomm::qti::sensor::SensorInterfaceStub,
        CommonAPI::Version
    > getSensorInterfaceInterfaceVersionStubDispatcher;

    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::com::qualcomm::qti::sensor::SensorInterfaceStub,
        std::tuple< >,
        std::tuple< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT>,
        std::tuple< >,
        std::tuple< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorReturnTDeployment_t>
    > registerSensorClientReqStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::com::qualcomm::qti::sensor::SensorInterfaceStub,
        std::tuple< >,
        std::tuple< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT>,
        std::tuple< >,
        std::tuple< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorReturnTDeployment_t>
    > deRegisterSensorClientReqStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::com::qualcomm::qti::sensor::SensorInterfaceStub,
        std::tuple< >,
        std::tuple< std::vector< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorInfoT >, int32_t>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::ArrayDeployment< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorInfoTDeployment_t >, CommonAPI::SomeIP::IntegerDeployment<int32_t>>
    > getSensorListReqStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::com::qualcomm::qti::sensor::SensorInterfaceStub,
        std::tuple< int32_t, float, int32_t>,
        std::tuple< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<int32_t>, CommonAPI::EmptyDeployment, CommonAPI::SomeIP::IntegerDeployment<int32_t>>,
        std::tuple< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorReturnTDeployment_t>
    > sensorConfigReqStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::com::qualcomm::qti::sensor::SensorInterfaceStub,
        std::tuple< int32_t, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorStateT>,
        std::tuple< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<int32_t>, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorStateTDeployment_t>,
        std::tuple< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorReturnTDeployment_t>
    > sensorControlReqStubDispatcher;
    
    SensorInterfaceSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        SensorInterfaceSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< SensorInterfaceStub>(_stub)),
        getSensorInterfaceInterfaceVersionStubDispatcher(&SensorInterfaceStub::lockInterfaceVersionAttribute, &SensorInterfaceStub::getInterfaceVersion, false, true),
        registerSensorClientReqStubDispatcher(
            &SensorInterfaceStub::RegisterSensorClientReq,
            false,
            _stub->hasElement(4),
            std::make_tuple(),
            std::make_tuple(&::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorReturnTDeployment))
        
        ,
        deRegisterSensorClientReqStubDispatcher(
            &SensorInterfaceStub::DeRegisterSensorClientReq,
            false,
            _stub->hasElement(5),
            std::make_tuple(),
            std::make_tuple(&::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorReturnTDeployment))
        
        ,
        getSensorListReqStubDispatcher(
            &SensorInterfaceStub::GetSensorListReq,
            false,
            _stub->hasElement(6),
            std::make_tuple(),
            std::make_tuple(static_cast< CommonAPI::SomeIP::ArrayDeployment< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorInfoTDeployment_t >* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr)))
        
        ,
        sensorConfigReqStubDispatcher(
            &SensorInterfaceStub::SensorConfigReq,
            false,
            _stub->hasElement(7),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr), static_cast< CommonAPI::EmptyDeployment* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr)),
            std::make_tuple(&::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorReturnTDeployment))
        
        ,
        sensorControlReqStubDispatcher(
            &SensorInterfaceStub::SensorControlReq,
            false,
            _stub->hasElement(8),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr), &::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorStateTDeployment),
            std::make_tuple(&::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorReturnTDeployment))
        
    {
        SensorInterfaceSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x7d01) }, &registerSensorClientReqStubDispatcher );
        SensorInterfaceSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x7d02) }, &deRegisterSensorClientReqStubDispatcher );
        SensorInterfaceSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x7d03) }, &getSensorListReqStubDispatcher );
        SensorInterfaceSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x7d04) }, &sensorConfigReqStubDispatcher );
        SensorInterfaceSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x7d05) }, &sensorControlReqStubDispatcher );
        // Provided events/fields
        {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0x80e8));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x80e9), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_EVENT, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
        }
        {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0x80e8));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x80ea), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_EVENT, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
        }
        {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0x80e8));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x80eb), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_EVENT, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
        }
        {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0x80e8));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x80ec), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_EVENT, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
        }
    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};

template <typename _Stub, typename... _Stubs>
void SensorInterfaceSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireSensorCapabilitiesEvent(const ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorServiceStateMaskT &_SensorCapabilitiesMask) {
    CommonAPI::Deployable< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorServiceStateMaskT, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorServiceStateMaskTDeployment_t> deployed_SensorCapabilitiesMask(_SensorCapabilitiesMask, &::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorServiceStateMaskTDeployment);
    CommonAPI::SomeIP::StubEventHelper<CommonAPI::SomeIP::SerializableArguments<  CommonAPI::Deployable< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorServiceStateMaskT, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorServiceStateMaskTDeployment_t > 
    >>
        ::sendEvent(
            *this,
            CommonAPI::SomeIP::event_id_t(0x80e9),
            false,
             deployed_SensorCapabilitiesMask 
    );
}

template <typename _Stub, typename... _Stubs>
void SensorInterfaceSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireSensorConfigUpdateEvent(const int32_t &_sensorId, const float &_samplingRate, const int32_t &_batchCount) {
    CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t>> deployed_sensorId(_sensorId, static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr));
    CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t>> deployed_batchCount(_batchCount, static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<CommonAPI::SomeIP::SerializableArguments<  CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t> > 
    ,  float
    ,  CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t> > 
    >>
        ::sendEvent(
            *this,
            CommonAPI::SomeIP::event_id_t(0x80ea),
            false,
             deployed_sensorId 
            , _samplingRate
            ,  deployed_batchCount 
    );
}

template <typename _Stub, typename... _Stubs>
void SensorInterfaceSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireSensorImuDataReadEvent(const std::vector< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorImuEventT > &_SensorImuEvent, const int32_t &_count) {
    CommonAPI::Deployable< std::vector< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorImuEventT >, CommonAPI::SomeIP::ArrayDeployment< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorImuEventTDeployment_t >> deployed_SensorImuEvent(_SensorImuEvent, static_cast< CommonAPI::SomeIP::ArrayDeployment< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorImuEventTDeployment_t >* >(nullptr));
    CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t>> deployed_count(_count, static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<CommonAPI::SomeIP::SerializableArguments<  CommonAPI::Deployable< std::vector< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorImuEventT >, CommonAPI::SomeIP::ArrayDeployment< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorImuEventTDeployment_t > > 
    ,  CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t> > 
    >>
        ::sendEvent(
            *this,
            CommonAPI::SomeIP::event_id_t(0x80eb),
            false,
             deployed_SensorImuEvent 
            ,  deployed_count 
    );
}

template <typename _Stub, typename... _Stubs>
void SensorInterfaceSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireSensorHeadingDataReadEvent(const std::vector< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorHeadEventT > &_sensorHeadEvent, const int32_t &_count) {
    CommonAPI::Deployable< std::vector< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorHeadEventT >, CommonAPI::SomeIP::ArrayDeployment< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorHeadEventTDeployment_t >> deployed_sensorHeadEvent(_sensorHeadEvent, static_cast< CommonAPI::SomeIP::ArrayDeployment< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorHeadEventTDeployment_t >* >(nullptr));
    CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t>> deployed_count(_count, static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<CommonAPI::SomeIP::SerializableArguments<  CommonAPI::Deployable< std::vector< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorHeadEventT >, CommonAPI::SomeIP::ArrayDeployment< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorHeadEventTDeployment_t > > 
    ,  CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t> > 
    >>
        ::sendEvent(
            *this,
            CommonAPI::SomeIP::event_id_t(0x80ec),
            false,
             deployed_sensorHeadEvent 
            ,  deployed_count 
    );
}


template <typename _Stub, typename... _Stubs>
void SensorInterfaceSomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {
}

template <typename _Stub, typename... _Stubs>
void SensorInterfaceSomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {
}

template <typename _Stub = ::v1::com::qualcomm::qti::sensor::SensorInterfaceStub, typename... _Stubs>
class SensorInterfaceSomeIPStubAdapter
    : public SensorInterfaceSomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    SensorInterfaceSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          SensorInterfaceSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace sensor
} // namespace qti
} // namespace qualcomm
} // namespace com
} // namespace v1

#endif // V1_COM_QUALCOMM_QTI_SENSOR_Sensor_Interface_SOMEIP_STUB_ADAPTER_HPP_
