
/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/com/qualcomm/qti/sensor/SensorInterfaceTypesSomeIPDeployment.hpp>

namespace v1 {
namespace com {
namespace qualcomm {
namespace qti {
namespace sensor {
namespace SensorInterfaceTypes_ {

// typecollection-specific deployments
SensorReturnTDeployment_t SensorReturnTDeployment(32, false);
SensorTypeTDeployment_t SensorTypeTDeployment(32, false);
SensorStateTDeployment_t SensorStateTDeployment(32, false);
SensorServiceStateMaskTDeployment_t SensorServiceStateMaskTDeployment(32, false);
::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorResponseTDeployment_t SensorResponseTDeployment(0, &::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorReturnTDeployment);
::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorControlRequestTDeployment_t SensorControlRequestTDeployment(0, static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr), &::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorStateTDeployment);

} // namespace SensorInterfaceTypes_
} // namespace sensor
} // namespace qti
} // namespace qualcomm
} // namespace com
} // namespace v1
