/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V1_COM_QUALCOMM_QTI_SENSOR_SENSOR_INTERFACE_SOMEIP_PROXY_HPP_
#define V1_COM_QUALCOMM_QTI_SENSOR_SENSOR_INTERFACE_SOMEIP_PROXY_HPP_

#include <v1/com/qualcomm/qti/sensor/SensorInterfaceProxyBase.hpp>
#include <v1/com/qualcomm/qti/sensor/SensorInterfaceSomeIPDeployment.hpp>
#include <v1/com/qualcomm/qti/sensor/SensorInterfaceTypesSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Proxy.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Event.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <string>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v1 {
namespace com {
namespace qualcomm {
namespace qti {
namespace sensor {

class SensorInterfaceSomeIPProxy
    : virtual public SensorInterfaceProxyBase,
      virtual public CommonAPI::SomeIP::Proxy {
public:
    SensorInterfaceSomeIPProxy(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection);

    virtual ~SensorInterfaceSomeIPProxy();

    virtual SensorCapabilitiesEvent& getSensorCapabilitiesEvent();

    virtual SensorConfigUpdateEvent& getSensorConfigUpdateEvent();

    virtual SensorImuDataReadEvent& getSensorImuDataReadEvent();

    virtual SensorHeadingDataReadEvent& getSensorHeadingDataReadEvent();

    virtual void RegisterSensorClientReq(CommonAPI::CallStatus &_internalCallStatus, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT &_SensorResponse, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> RegisterSensorClientReqAsync(RegisterSensorClientReqAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    virtual void DeRegisterSensorClientReq(CommonAPI::CallStatus &_internalCallStatus, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT &_SensorResponse, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> DeRegisterSensorClientReqAsync(DeRegisterSensorClientReqAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    virtual void GetSensorListReq(CommonAPI::CallStatus &_internalCallStatus, std::vector< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorInfoT > &_SensorList, int32_t &_count, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> GetSensorListReqAsync(GetSensorListReqAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    virtual void SensorConfigReq(int32_t _sensorId, float _samplingRate, int32_t _batchCount, CommonAPI::CallStatus &_internalCallStatus, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT &_SensorResponse, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> SensorConfigReqAsync(const int32_t &_sensorId, const float &_samplingRate, const int32_t &_batchCount, SensorConfigReqAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    virtual void SensorControlReq(int32_t _sensorId, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorStateT _sensorState, CommonAPI::CallStatus &_internalCallStatus, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorReturnT &_SensorResponse, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> SensorControlReqAsync(const int32_t &_sensorId, const ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorStateT &_sensorState, SensorControlReqAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    virtual void getOwnVersion(uint16_t &_major, uint16_t &_minor) const;

    virtual std::future<void> getCompletionFuture();

private:
    CommonAPI::SomeIP::Event<SensorCapabilitiesEvent, CommonAPI::Deployable< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorServiceStateMaskT, ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorServiceStateMaskTDeployment_t >> sensorCapabilities_;
    CommonAPI::SomeIP::Event<SensorConfigUpdateEvent, CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t> >, CommonAPI::Deployable< float, CommonAPI::EmptyDeployment >, CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t> >> sensorConfigUpdate_;
    CommonAPI::SomeIP::Event<SensorImuDataReadEvent, CommonAPI::Deployable< std::vector< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorImuEventT >, CommonAPI::SomeIP::ArrayDeployment< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorImuEventTDeployment_t > >, CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t> >> sensorImuDataRead_;
    CommonAPI::SomeIP::Event<SensorHeadingDataReadEvent, CommonAPI::Deployable< std::vector< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes::SensorHeadEventT >, CommonAPI::SomeIP::ArrayDeployment< ::v1::com::qualcomm::qti::sensor::SensorInterfaceTypes_::SensorHeadEventTDeployment_t > >, CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t> >> sensorHeadingDataRead_;

    std::promise<void> completed_;
};

} // namespace sensor
} // namespace qti
} // namespace qualcomm
} // namespace com
} // namespace v1

#endif // V1_COM_QUALCOMM_QTI_SENSOR_Sensor_Interface_SOMEIP_PROXY_HPP_
